### ISSUE TITLE
clear local torrent cache cause error

### ISSUE THREAD

**Issue by minhgi** [nixgates/plugin.video.seren#168]
2019-09-04 08:10:12.187 T:10800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'thread.error'>
                                            Error Contents: release unlocked lock
                                            Traceback (most recent call last):
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 782, in <module>
                                                api(api_params)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 539, in api
                                                database.torrent_cache_clear()
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\database.py", line 392, in torrent_cache_clear
                                                cursor_lock.release()
                                            error: release unlocked lock
                                            -->End of Python script error report<--

**Comment by nixgates** [comment]
Ah yea, I can see that error. It should be superficial and not something to be overly concerned with.

I'll make the adjustments for the next hot fix so it no longer happens.

Thanks for this! :)

**Comment by minhgi** [comment]
Oh nice.  didn't know if it was working or just a message error.  Thanks for looking into it.

**Comment by BinaryAssault** [comment]
@nixgates I noticed this too while troubleshooting an issue, I created a pull request for this one.

**Comment by nixgates** [comment]
@BinaryAssault Thanks for the PR but I'm going to have to cancel it as it's already been fixed in the current Dev branch.

Much appreciated though :)

**Comment by nixgates** [comment]
Closing issue, fixed in latest update
