### ISSUE TITLE
My Movies watchlist error; returns no results. Only Seren effected

### ISSUE THREAD

**Issue by metaltermite** [nixgates/plugin.video.seren#173]
Ever since the initial public beta release of Seren the addon has been incapable of reading my movie watchlist. Upon clicking watchlist, Seren does nothing and outputs "Seren error, click the log for more information".

I have enabled debugging log mode.  Full logs uploaded to [Pastebin](https://pastebin.com/raw/VACHkwSH).

- I have attempted this on fresh Kodi installs over different devices and have received the same results, while other add-ons are capable of reading my Trakt movie watchlist.
- Yes, I have authorized and reauthorized Seren with Trakt many times and it utilizes other personal Trakt account features.
- My watchlist has 180 items (if that might have anything to do with it)

I believe this is the pertinent part of the logs:
```
2019-09-11 15:32:02.759 T:7708  NOTICE: Starting Kodi (18.3 Git:20190619-89472b7d69). Platform: Windows NT x86 64-bit
2019-09-11 15:32:02.759 T:7708  NOTICE: Using Release Kodi x64 build
2019-09-11 15:32:02.759 T:7708  NOTICE: Kodi compiled 2019-06-27 by MSVC 191627031 for Windows NT x86 64-bit version 10.0 (0x0A000006)
2019-09-11 15:32:02.759 T:7708  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362

2019-09-11 15:32:02.824 T:7708  NOTICE: ADDON: plugin.video.seren v1.4.8 installed

2019-09-11 15:33:17.645 T:13752   DEBUG: -->Python Interpreter Initialized<--
2019-09-11 15:33:17.645 T:13752   DEBUG: CPythonInvoker(24, C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): the source file to load is "C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py"
2019-09-11 15:33:17.646 T:13752   DEBUG: CPythonInvoker(24, C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): setting the Python path to C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren;C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.addon.common\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.addon.signals\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.beautifulsoup4\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.certifi\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.chardet\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.dateutil\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.idna\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.metahandler\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.myconnpy\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.six\lib;C:\Users\echo\AppData\Roaming\Kodi\addons\script.module.urllib3\lib;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python\DLLs;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python\Lib;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\python27.zip;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python\lib\plat-win;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python\lib\lib-tk;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python;C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.3.500.0_x64__4n2hpmxwrvr6p\system\python\lib\site-packages
2019-09-11 15:33:17.646 T:13752   DEBUG: CPythonInvoker(24, C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): entering source directory C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren
2019-09-11 15:33:17.646 T:13752   DEBUG: CPythonInvoker(24, C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): instantiating addon using automatically obtained id of "plugin.video.seren" dependent on version 2.19.0 of the xbmc.python api

2019-09-11 15:33:19.126 T:13752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: object of type 'NoneType' has no len()
                                            Traceback (most recent call last):
                                              File "C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 782, in <module>
                                                api(api_params)
                                              File "C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 154, in api
                                                movieMenus.Menus().myMovieWatchlist()
                                              File "C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\gui\movieMenus.py", line 109, in myMovieWatchlist
                                                self.commonListBuilder(trakt_list)
                                              File "C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\gui\movieMenus.py", line 337, in commonListBuilder
                                                if len(trakt_list) == 0:
                                            TypeError: object of type 'NoneType' has no len()
                                            -->End of Python script error report<--
2019-09-11 15:33:19.127 T:13752   DEBUG: CPythonInvoker::onExecutionDone(24, C:\Users\echo\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py)
2019-09-11 15:33:19.141 T:7708   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-09-11 15:33:19.189 T:13752    INFO: Python interpreter stopped
2019-09-11 15:33:19.189 T:13752   DEBUG: Thread LanguageInvoker 13752 terminating
2019-09-11 15:33:19.199 T:8140   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.seren/?action=moviesMyWatchlist
2019-09-11 15:33:19.199 T:8140   DEBUG: Thread waiting 8140 terminating
2019-09-11 15:33:19.206 T:7708   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-09-11 15:33:19.207 T:7708   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=moviesMyWatchlist) failed
2019-09-11 15:33:19.207 T:7708   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.seren/?action=myMovies)
2019-09-11 15:33:19.208 T:7708   DEBUG:   ParentPath = [plugin://plugin.video.seren/]
2019-09-11 15:33:19.209 T:7708   DEBUG: Loading items: 4, directory: plugin://plugin.video.seren/?action=myMovies sort method: 0, ascending: false
2019-09-11 15:33:19.214 T:14556   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.seren] took 6 ms
2019-09-11 15:33:19.222 T:10712   DEBUG: Thread BackgroundLoader start, auto delete: false
```
Let me know if you need access to my watchlist.

**Comment by metaltermite** [comment]
A few days ago I sent you a DM on Reddit with my Trakt username. If you didn't receive it let me know.

**Comment by nixgates** [comment]
@metaltermite hey just wanted to check if this issue is still present, sorry for the long delay

**Comment by metaltermite** [comment]
@nixgates Done. Sent you a DM on Reddit. Also noticed my watchlist automatically sorts to _random,asc_, not sure if that's causing the problem and cannot test it atm.

**Comment by drinfernoo** [comment]
@metaltermite You can configure the default sorting for collections and watchlists on Trakt's website, in your account settings.

**Comment by nixgates** [comment]
@metaltermite your profile is set to private and I can't access your list to test against

Would you mind disabling your privacy settings temporarily, let me know on here that you've done it and I'll try the tests to identify the issue.

**Comment by metaltermite** [comment]
@nixgates privacy should be disabled now. let me know if there's anything else you need.
