### ISSUE TITLE
Trakt sync broken because of script.module.beautifulsoup4 upgrade to 4.6.3

### ISSUE THREAD

**Issue by pogarek** [nixgates/plugin.video.seren#182]
I get the following when I try to sync trakt :
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named html.entities
                                            Traceback (most recent call last):
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/plugin.video.seren/seren.py", line 782, in <module>
                                                api(api_params)
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/plugin.video.seren/seren.py", line 719, in api
                                                from resources.lib.modules.trakt_sync.activities import TraktSyncDatabase
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 3, in <module>
                                                from resources.lib.modules.trakt_sync import shows
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/shows.py", line 6, in <module>
                                                from resources.lib.indexers import trakt, imdb, tmdb
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/plugin.video.seren/resources/lib/indexers/imdb.py", line 8, in <module>
                                                from bs4 import BeautifulSoup, SoupStrainer
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "/private/var/mobile/Containers/Data/Application/48164B99-2985-46C2-BB77-576D13C6F582/Library/Caches/Kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 14, in <module>
                                                from html.entities import codepoint2name
                                            ImportError: No module named html.entities
                                            -->End of Python script error report<--
```

Seems like script.module.beautifulsoup4 starting on 4.6.3 is on Python 3 now...

**Comment by pogarek** [comment]
the updated dependency got pulled out.
