### ISSUE TITLE
Unhandled request errors

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#225]
I get some unhandled errors in _request_core in "~/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py" due to blocked sites.  I was able to stop the errors in my log with the following change:

```
    def _request_core(self, request, sequental = None):
        self.has_timeout_exc = False
        self.exc_msg = ''

        if sequental is None:
            sequental = self._sequental

        response_err = lambda: None
        response_err.status_code = 501

        try:
            response = None
            if sequental is False:
#                response = request()
#                response_err = response
		try:
			response = request()
			response_err = response
	                self._verify_response(response)
		except:
			response_err = response
		try:
			self._verify_response(response)
		except:
			pass

                return response

            with self._lock:
                if self._should_wait:
                    time.sleep(self._wait)
                self._should_wait = True
                response = request()

            response_err = response
            self._verify_response(response)

            return response
        except:
            if self.exc_msg == '':
              exc = traceback.format_exc(limit=1)
              if 'ConnectTimeout' in exc or 'ReadTimeout' in exc:
                  self.has_timeout_exc = True
                  self.exc_msg = 'request timed out'
              elif 'Cloudflare' in exc or '!!Loop Protection!!' in exc:
                  self.exc_msg = 'failed Cloudflare protection'
              else:
                  self.exc_msg = 'failed - %s' % exc

            tools.log('%s %s' % (request.url, self.exc_msg), 'notice')

            return response_err
```

Although i suspect there is a slightly better way to handle the errors, here is the relevant section from my logs:

```
2020-02-15 10:20:09.984 T:2370818784  NOTICE: SEREN: https://eztv.io failed - Traceback (most recent call last):
                                              File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 83, in _request_core
                                                response = request()
                                            ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2020-02-15 10:20:12.590 T:1694868192  NOTICE: SEREN: https://movcr.tv/search/search.php?q=brooklyn+nine+nine+S05E02 response status code 404
2020-02-15 10:20:13.182 T:2370818784  NOTICE: SEREN: https://eztv.io failed - Traceback (most recent call last):
                                              File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 83, in _request_core
                                                response = request()
                                            ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2020-02-15 10:20:13.252 T:1678082784  NOTICE: SEREN: https://torrentz2.eu/search?f=brooklyn+nine+nine+S05E02&safe=1 failed - Traceback (most recent call last):
                                              File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 83, in _request_core
                                                response = request()
                                            ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by drinfernoo** [comment]
If you submitted these as a PR, it would be super easy to diff and see what the actual changes you made were 👌

**Comment by henryjfry** [comment]
Ok i just added a pull request now.
https://github.com/a4k-openproject/a4kScrapers/pull/69

Can I ask is it possible to raise a pull request without forking the whole addon?

**Comment by drinfernoo** [comment]
@henryjfry Unfortunately not, just because of how git works.

**Comment by henryjfry** [comment]
Ok cool, I wasn't sure if I was missing something.

So are you going to implement something like my "fix" or would you have a more elegant solution?

**Comment by drinfernoo** [comment]
@henryjfry Neither Seren or a4kScrapers are my project 😅 I'm just around to help keep things going 👌

**Comment by nixgates** [comment]
Sorry this is not for the Seren project
