### ISSUE TITLE
Bug playing cached real debrid torrent

### ISSUE THREAD

**Issue by 0xfoo** [nixgates/plugin.video.seren#242]
I am trying a file provided by torrentapi that is cached in real debrid (confirmed through their webui)
but it's failing with the following log 
```
                                            Container -- Attempting to Play Item...:
                                            {u'info': u'play', u'widget': u'True', u'episode': u'2', u'tmdb_id': u'100052', u'season': u'1', u'type': u'episode'}
2020-04-26 23:13:45.671 T:7939   ERROR: Traceback (most recent call last):
2020-04-26 23:13:45.671 T:7939   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 317, in resolve_magnet
2020-04-26 23:13:45.673 T:7939   ERROR:     if link.endswith('rar'):
2020-04-26 23:13:45.673 T:7939   ERROR: AttributeError: 'NoneType' object has no attribute 'endswith'
2020-04-26 23:13:48.050 T:7939   ERROR: Traceback (most recent call last):
2020-04-26 23:13:48.050 T:7939   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 317, in resolve_magnet
2020-04-26 23:13:48.051 T:7939   ERROR:     if link.endswith('rar'):
2020-04-26 23:13:48.051 T:7939   ERROR: AttributeError: 'NoneType' object has no attribute 'endswith'
```
Base 64 Magnet : bWFnbmV0Oj94dD11cm46YnRpaDoxOGYwOTNmZDZlMThiZWM2NDZmNjY1N2E2MjcwZTIwOThhZjBkOWUxJmRuPVRoZS5FbmdsaXNoLkdhbWUuUzAxLjEwODBwLk5GLldFQlJpcC54MjY1LjEwYml0LkhEUi5ERFA1LjEtR0hPU1RTJTVCcmFydHYlNUQmdHI9aHR0cCUzQSUyRiUyRnRyYWNrZXIudHJhY2tlcmZpeC5jb20lM0E4MCUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRjkucmFyYmcubWUlM0EyNzgwJnRyPXVkcCUzQSUyRiUyRjkucmFyYmcudG8lM0EyODUw

**Comment by 0xfoo** [comment]
Adding the file to my files and then trying to play it from there does not work too 

`2020-04-27 00:13:39.408 T:10709  NOTICE: [plugin.video.themoviedb.helper]
                                            Container -- Attempting to Play Item...:
                                            {u'info': u'play', u'widget': u'True', u'episode': u'2', u'tmdb_id': u'100052', u'season': u'1', u'type': u'episode'}
2020-04-27 00:14:56.856 T:10743   ERROR: Traceback (most recent call last):
2020-04-27 00:14:56.856 T:10743   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 298, in dispatch
2020-04-27 00:14:56.859 T:10743   ERROR:     raise Exception
2020-04-27 00:14:56.859 T:10743   ERROR: Exception
2020-04-27 00:14:56.939 T:5066   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.seren/?action=getSources&actionArgs=%7B%22episode%22%3A%202%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%201%2C%20%22trakt_id%22%3A%20158896%7D]`

**Comment by 0xfoo** [comment]
Found the source of the problem it was the vpn
