### ISSUE TITLE
Seren Next Up Error

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#263]
Hi, Is Seren Next Up not working for anyone? I'm getting error that it can't be opened in all my Kodi instances on multiple systems. I tried revoking trakt authentication and also clearing cache but nothing seems to work. This issue is only happening on Android and not on Windows. Please help!

Here is my log:

2020-10-19 15:54:23.105 T:3996   ERROR: Traceback (most recent call last):
2020-10-19 15:54:23.107 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 57, in sync_activities
2020-10-19 15:54:23.127 T:3996   ERROR:     success = self._remove_old_meta_items('shows')
2020-10-19 15:54:23.127 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 606, in _remove_old_meta_items
2020-10-19 15:54:23.128 T:3996   ERROR:     for i in range(2, int(trakt_api.response_headers['X-Pagination-Page-Count']) + 1):
2020-10-19 15:54:23.128 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
2020-10-19 15:54:23.132 T:3996   ERROR:     return self._store[key.lower()][1]
2020-10-19 15:54:23.133 T:3996   ERROR: KeyError: 'x-pagination-page-count'
2020-10-19 15:54:23.392 T:3996   ERROR: Traceback (most recent call last):
2020-10-19 15:54:23.398 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 75, in sync_activities
2020-10-19 15:54:23.399 T:3996   ERROR:     success = self._remove_old_meta_items('movies')
2020-10-19 15:54:23.400 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 606, in _remove_old_meta_items
2020-10-19 15:54:23.400 T:3996   ERROR:     for i in range(2, int(trakt_api.response_headers['X-Pagination-Page-Count']) + 1):
2020-10-19 15:54:23.401 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
2020-10-19 15:54:23.401 T:3996   ERROR:     return self._store[key.lower()][1]
2020-10-19 15:54:23.402 T:3996   ERROR: KeyError: 'x-pagination-page-count'
2020-10-19 15:54:24.448 T:3996   ERROR: Traceback (most recent call last):
2020-10-19 15:54:24.449 T:3996   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 104, in sync_activities
2020-10-19 15:54:24.450 T:3996   ERROR:     limitOverride=500)])
2020-10-19 15:54:24.450 T:3996   ERROR: TypeError: 'NoneType' object is not iterable
2020-10-19 15:54:25.695 T:3996   ERROR: SEREN: Unable to connect to Trakt
2020-10-19 15:54:39.682 T:4780   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 14, in <module>
                                                router.dispatch(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 632, in dispatch
                                                tvshowMenus.Menus().myNextUp()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 183, in myNextUp
                                                watched_list = sorted(watched_list, key=lambda i: i['last_watched_at'], reverse=True)
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2020-10-19 15:54:40.018 T:3439   ERROR: GetDirectory - Error getting plugin://plugin.video.seren/?action=showsNextUp
2020-10-19 15:54:48.627 T:3976 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://USERNAME:PASSWORD@192.168.0.116/Thumbnails/0/0e3ee2ed.jpg
2020-10-19 15:55:04.422 T:3439   ERROR: GetDirectory - Error getting Weather
2020-10-19 15:55:04.596 T:3439   ERROR: GetDirectory - Error getting Settings
2020-10-19 15:57:32.702 T:3224   ERROR: Previous line repeats 1 times.
2020-10-19 15:57:32.705 T:3224  NOTICE: Samba is idle. Closing the remaining connections
2020-10-19 16:00:59.823 T:3257  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2020-10-19 16:00:59.880 T:3257  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
2020-10-19 16:01:00.498 T:8013   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Action & Adventure.png
2020-10-19 16:01:00.501 T:8014   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Sci-Fi & Fantasy.png
2020-10-19 16:01:03.666 T:3224 WARNING: Trying to add unsupported control type 1
2020-10-19 16:01:18.324 T:8173 WARNING: Previous line repeats 1 times.
2020-10-19 16:01:18.325 T:8173   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 14, in <module>
                                                router.dispatch(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 632, in dispatch
                                                tvshowMenus.Menus().myNextUp()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 183, in myNextUp
                                                watched_list = sorted(watched_list, key=lambda i: i['last_watched_at'], reverse=True)
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2020-10-19 16:01:18.565 T:8172   ERROR: GetDirectory - Error getting plugin://plugin.video.seren/?action=showsNextUp
2020-10-19 16:01:18.578 T:3224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=showsNextUp) failed
2020-10-19 16:01:59.751 T:8219   ERROR: Traceback (most recent call last):
2020-10-19 16:01:59.751 T:8219   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 137, in refreshToken
2020-10-19 16:01:59.755 T:8219   ERROR:     tools.setSetting('trakt.auth', response['access_token'])
2020-10-19 16:01:59.755 T:8219   ERROR: KeyError: 'access_token'
2020-10-19 16:01:59.755 T:8219   ERROR: SEREN: Failed to refresh Trakt Access Token
2020-10-19 16:02:00.155 T:8219   ERROR: SEREN: Failed to perform request even after token refresh
2020-10-19 16:03:21.373 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 1
2020-10-19 16:03:21.764 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 2
2020-10-19 16:03:22.152 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 3
2020-10-19 16:03:22.554 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 4
2020-10-19 16:03:22.962 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 5
2020-10-19 16:03:23.368 T:8305   ERROR: SEREN: Trakt failed to reply on multiple attempts, URL: /sync/watched/shows?extended=full&limit=20
2020-10-19 16:03:23.373 T:8305   ERROR: Traceback (most recent call last):
2020-10-19 16:03:23.373 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 162, in sync_activities
2020-10-19 16:03:23.377 T:8305   ERROR:     self._sync_watched_episodes()
2020-10-19 16:03:23.377 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 423, in _sync_watched_episodes
2020-10-19 16:03:23.377 T:8305   ERROR:     for show in trakt_watched for season in show['seasons'] for episode in season['episodes']]
2020-10-19 16:03:23.378 T:8305   ERROR: TypeError: 'NoneType' object is not iterable
2020-10-19 16:03:26.806 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 1
2020-10-19 16:03:27.219 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 2
2020-10-19 16:03:27.632 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 3
2020-10-19 16:03:28.001 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 4
2020-10-19 16:03:28.408 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 5
2020-10-19 16:03:28.810 T:8305   ERROR: SEREN: Trakt failed to reply on multiple attempts, URL: sync/watched/shows?limit=20
2020-10-19 16:03:28.813 T:8305   ERROR: Traceback (most recent call last):
2020-10-19 16:03:28.814 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 182, in sync_activities
2020-10-19 16:03:28.814 T:8305   ERROR:     self._sync_unwatched()
2020-10-19 16:03:28.814 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 443, in _sync_unwatched
2020-10-19 16:03:28.815 T:8305   ERROR:     for show in trakt_watched_episodes for season in show['seasons'] for episode
2020-10-19 16:03:28.815 T:8305   ERROR: TypeError: 'NoneType' object is not iterable
2020-10-19 16:03:29.291 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 1
2020-10-19 16:03:29.654 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 2
2020-10-19 16:03:30.062 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 3
2020-10-19 16:03:30.467 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 4
2020-10-19 16:03:30.852 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 5
2020-10-19 16:03:31.230 T:8305   ERROR: SEREN: Trakt failed to reply on multiple attempts, URL: sync/collection/shows?extended=full&limit=20
2020-10-19 16:03:31.233 T:8305   ERROR: Traceback (most recent call last):
2020-10-19 16:03:31.233 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 198, in sync_activities
2020-10-19 16:03:31.233 T:8305   ERROR:     self._sync_collection_shows()
2020-10-19 16:03:31.233 T:8305   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 503, in _sync_collection_shows
2020-10-19 16:03:31.234 T:8305   ERROR:     for show in trakt_collection for season in show['seasons'] for episode
2020-10-19 16:03:31.234 T:8305   ERROR: TypeError: 'NoneType' object is not iterable
2020-10-19 16:03:35.844 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 1
2020-10-19 16:03:36.239 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 2
2020-10-19 16:03:36.619 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 3
2020-10-19 16:03:36.985 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 4
2020-10-19 16:03:37.425 T:8305   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 5
2020-10-19 16:03:38.586 T:8305   ERROR: SEREN: Trakt failed to reply on multiple attempts, URL: sync/collection/shows?limit=20
2020-10-19 16:04:38.304 T:3224   ERROR: Control 500 in window 10001 has been asked to focus, but it can't
2020-10-19 16:04:52.240 T:8405   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 1
2020-10-19 16:04:52.670 T:8405   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 2
2020-10-19 16:04:53.979 T:8405   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 3
2020-10-19 16:04:54.386 T:8405   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 4
2020-10-19 16:04:54.803 T:8405   ERROR: SEREN: Failed to perform Trakt Get request, re-trying. Attempts: 5
2020-10-19 16:04:55.194 T:8405   ERROR: SEREN: Trakt failed to reply on multiple attempts, URL: users/me/watched/shows?limit=20
2020-10-19 16:04:55.206 T:8405   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 14, in <module>
                                                router.dispatch(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 632, in dispatch
                                                tvshowMenus.Menus().myNextUp()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 183, in myNextUp
                                                watched_list = sorted(watched_list, key=lambda i: i['last_watched_at'], reverse=True)
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2020-10-19 16:04:55.442 T:8404   ERROR: GetDirectory - Error getting plugin://plugin.video.seren/?action=showsNextUp
2020-10-19 16:04:55.447 T:3224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=showsNextUp) failed

**Comment by ShibajiCh** [comment]
This issue has been fixed by Trakt. I'm closing this ticket.
