### ISSUE TITLE
[BUG] Any "Specials" causing Seren error

### ISSUE THREAD

**Issue by cdensel** [nixgates/plugin.video.seren#396]
Firstly, thanks for all your hard work. 

I noticed this bug when searching for "Euphoria". Under "Specials", click the first episode "Trouble Don't Last Always".
As soon as you click it, get "Seren Error: Check the logs for more information". 

Logs of error included below.

System: Raspi 4 LibreELEC 9.2.6
Kodi: 18.9.0
Real Debrid & Trakt
Metalocation: Trakt

All other series working fine, just seems to be issue with "Specials". Was able to recreate with "The Sopranos" and "Specials".
 

2021-01-12 10:29:12.120 T:3012014096   DEBUG: StartScript - calling plugin Seren('plugin://plugin.video.seren/','8','?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522episode%2522%252C%2520%2522trakt_id%2522%253A%25204539408%252C%2520%2522trakt_season_id%2522%253A%2520231781%252C%2520%2522trakt_show_id%2522%253A%2520144629%257D&from_widget=false','resume:false')
2021-01-12 10:29:12.121 T:3012014096   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 20 for script /storage/.kodi/addons/plugin.video.seren/seren.py
2021-01-12 10:29:12.121 T:2499847024    INFO: initializing python engine.
2021-01-12 10:29:12.121 T:2499847024   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.seren/seren.py): start processing
2021-01-12 10:29:12.121 T:2499847024   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.seren/seren.py): entering source directory /storage/.kodi/addons/plugin.video.seren
2021-01-12 10:29:12.121 T:2499847024   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.seren/seren.py): instantiating addon using automatically obtained id of "plugin.video.seren" dependent on version 2.26.0 of the xbmc.python api
2021-01-12 10:29:12.134 T:2499847024   DEBUG: CAddonSettings[plugin.video.seren]: loading setting definitions
2021-01-12 10:29:12.134 T:2499847024   DEBUG: CAddonSettings[plugin.video.seren]: trying to load setting definitions from old format...
2021-01-12 10:29:12.141 T:2490364784   DEBUG: Thread scriptobs start, auto delete: false
2021-01-12 10:29:12.147 T:2499847024   DEBUG: CAddonSettings[plugin.video.seren]: loading setting values
2021-01-12 10:29:12.168 T:2499847024    INFO: SEREN: Seren, Running Path - {u'action': u'getSources', u'from_widget': u'false', u'action_args': {u'trakt_id': 4539408, u'trakt_show_id': 144629, u'mediatype': u'episode', u'trakt_season_id': 231781}}
2021-01-12 10:29:12.228 T:2499847024   DEBUG: SEREN: Fetching Episode list from sync database
2021-01-12 10:29:12.278 T:2499847024   DEBUG: SEREN: Updated required episodes
2021-01-12 10:29:12.292 T:2499847024   DEBUG: SEREN: Processing Time -    125ms - getSources
2021-01-12 10:29:12.295 T:2499847024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 117, in dispatch
                                                item_information = tools.get_item_information(action_args)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/common/tools.py", line 268, in get_item_information
                                                action_args["trakt_id"], action_args["trakt_show_id"]
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 422, in get_episode
                                                (trakt_id, trakt_id),
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2021-01-12 10:29:12.295 T:2499847024   DEBUG: onExecutionDone(20, /storage/.kodi/addons/plugin.video.seren/seren.py)
2021-01-12 10:29:12.341 T:3012014096   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-01-12 10:29:12.343 T:3012014096   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-01-12 10:29:12.450 T:2499847024    INFO: Python interpreter stopped
2021-01-12 10:29:12.450 T:2499847024    INFO: Previous line repeats 8 times.
2021-01-12 10:29:12.450 T:2499847024   DEBUG: Thread LanguageInvoker 2499847024 terminating
2021-01-12 10:29:12.463 T:2490364784   DEBUG: Thread scriptobs 2490364784 terminating
2021-01-12 10:29:12.470 T:3012014096   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-01-12 10:29:12.471 T:3012014096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522episode%2522%252C%2520%2522trakt_id%2522%253A%25204539408%252C%2520%2522trakt_season_id%2522%253A%2520231781%252C%2520%2522trakt_show_id%2522%253A%2520144629%257D&from_widget=false]
2021-01-12 10:29:12.471 T:3012014096   DEBUG: Playlist Player: no more playable items... aborting playback
2021-01-12 10:29:12.471 T:2490364784   DEBUG: Thread BackgroundLoader start, auto delete: false
2021-01-12 10:29:12.479 T:2490364784   DEBUG: Thread BackgroundLoader 2490364784 terminating

**Comment by nixgates** [comment]
@cdensel fixed for next update :+1:

**Comment by cdensel** [comment]
Excellent! Thanks for your dedication and hard work.

**Comment by nixgates** [comment]
@cdensel can you confirm that you can now browse the specials?

**Comment by cdensel** [comment]
Tested and confirmed working.
Thanks!
