### ISSUE TITLE
[BUG] Searching for show beginning with numbers causes crash. E.g "24 Hours"

### ISSUE THREAD

**Issue by cdensel** [nixgates/plugin.video.seren#397]
System: Raspi 4 LibreELEC 9.2.6
Kodi: 18.9.0
Real Debrid & Trakt

In Shows, search for "24 hours". Seren errors straightaway. Logs below.

2021-01-12 10:36:52.513 T:3012014096   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2021-01-12 10:36:52.513 T:3012014096   DEBUG: HandleKey: return (0xf00d) pressed, trying keyboard action 7
2021-01-12 10:36:52.921 T:3012014096   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
2021-01-12 10:36:53.021 T:2499847024   DEBUG: SEREN: Fetching show list from sync database
2021-01-12 10:36:53.037 T:2499847024    INFO: SEREN: Inserting Shows into sync database: []
2021-01-12 10:36:53.100 T:2490364784   DEBUG: SEREN: 1 items require season milling
2021-01-12 10:36:53.298 T:2490364784    INFO: SEREN: Inserting seasons into sync database: []
2021-01-12 10:36:53.311 T:2490364784    INFO: SEREN: Inserting episodes into sync database: []
2021-01-12 10:36:53.354 T:2499847024   DEBUG: SEREN: Show list update and milling compelete
2021-01-12 10:36:53.417 T:2499847024   ERROR: EXCEPTION: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
2021-01-12 10:36:53.419 T:2499847024   ERROR: SEREN: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 160, in _common_menu_builder
                                                if item is not None
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 1054, in add_directory_item
                                                item.setInfo("video", info)
                                            TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
2021-01-12 10:36:53.419 T:2552849264   DEBUG: Thread waiting 2552849264 terminating
2021-01-12 10:36:53.419 T:2499847024 WARNING: Attempt to use invalid handle 11
2021-01-12 10:36:53.420 T:2499847024 WARNING: Previous line repeats 2 times.
2021-01-12 10:36:53.420 T:2499847024   DEBUG: SEREN: Processing Time -   6930ms - showsSearch
2021-01-12 10:36:53.423 T:2499847024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 290, in dispatch
                                                tvshowMenus.Menus().shows_search(action_args)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 404, in shows_search
                                                self.shows_search_results(query)
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 418, in shows_search_results
                                                if float(show["trakt_object"]["info"]["score"]) > 0
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 101, in show_list_builder
                                                **params
                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 173, in _common_menu_builder
                                                raise e
                                            TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                            -->End of Python script error report<--
2021-01-12 10:36:53.423 T:2499847024   DEBUG: onExecutionDone(23, /storage/.kodi/addons/plugin.video.seren/seren.py)
2021-01-12 10:36:53.446 T:3012014096   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-01-12 10:36:53.450 T:2552849264   DEBUG: Thread BackgroundLoader start, auto delete: false
2021-01-12 10:36:53.457 T:2552849264   DEBUG: Thread BackgroundLoader 2552849264 terminating
2021-01-12 10:36:53.479 T:3012014096   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-01-12 10:36:53.586 T:2499847024    INFO: Python interpreter stopped
2021-01-12 10:36:53.586 T:2499847024    INFO: Previous line repeats 4 times.
2021-01-12 10:36:53.586 T:2499847024   DEBUG: Thread LanguageInvoker 2499847024 terminating
2021-01-12 10:36:59.220 T:3012014096   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Comment by nixgates** [comment]
@cdensel this doesn't look so much like an issue with handling numbers rather an issue with handling some of the metadata that comes for the items in the search. I personally didn't have an issue pulling that search title, could you perhaps let me know the following settings so I can investigate further:

Interface > Metadata location
Kodi Language that's set

**Comment by cdensel** [comment]
Hi,

Thanks for prompt response. I checked that setting and for some reason it
was set to "TMDb". Set it Trakt and issue is now resolved.


Thanks, Cd
