### ISSUE TITLE
[BUG] Trakt lists, collection and resume points not working as it should be

### ISSUE THREAD

**Issue by queensryche6** [nixgates/plugin.video.seren#411]
**Describe the bug**
After 2.0.12 trakt collection not populates with whatever i have added after the new version. Same for watchlist. Popular recent shows gives the above log error. Trending show lists shows only the list New Shows multiple times. Popular show lists shows only netflix and IMDB: top rated tv shows multiple times.
**To Reproduce**
1. Go to 'Discover TV Shows'
2. Click on 'Trending or Popular show lists'

OR

1. Go to 'My TV Shows'
2. Click on 'Collection' or 'Watchlist'

Moreover, movies do not resume from where left off across different devices. TV shows only resume if cached is cleared and trakt is synced prior of playing.

Thanks for all your hard work!!!

<img width="1488" alt="Screenshot 2021-01-15 at 12 05 30 PM" src="https://user-images.githubusercontent.com/2001160/104711412-02abf980-572a-11eb-8885-4818e8e602ad.png">
<img width="1488" alt="Screenshot 2021-01-15 at 12 06 12 PM" src="https://user-images.githubusercontent.com/2001160/104711474-17888d00-572a-11eb-9365-d38afdb1e564.png">

 - Kodi Version 18.9.0 
On a Mac mini, Nvidia shield and MIBOX 3

**Logs**
Kodi/addons/plugin.video.seren/seren.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon4xbmc7MonitorE
2021-01-15 11:59:10.385 T:13158699008   ERROR: SEREN: WITH requested(trakt_id) AS (VALUES (None),(157322),(157873),(158101),(161611),(163686),(157684),(160721),(155074),(162167),(170822),(163974),(152618),(157894),(166087),(156001),(159939),(164599),(161602),(160876)) select r.trakt_id as trakt_id from requested as r inner join shows as db on r.trakt_id == db.trakt_id left join shows_meta as m on db.trakt_id == id and type = 'trakt' where 1=1 AND Datetime(air_date) < Datetime('now') AND watched_episodes < episode_count
2021-01-15 11:59:10.387 T:13158699008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such column: None
                                            Traceback (most recent call last):
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 717, in dispatch
                                                Menus().shows_popular_recent()
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 238, in shows_popular_recent
                                                "shows/popular", years=year_range, page=g.PAGE, extended="full"
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 30, in extract_trakt_page
                                                url, "shows", **params
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/__init__.py", line 986, in _extract_trakt_page
                                                _handle_page(page)
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/__init__.py", line 971, in _handle_page
                                                result.extend(self.execute_sql(query).fetchall())
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 223, in execute_sql
                                                return self._execute_query(data, connection.cursor(), query)
                                              File "/Users/queensryche6/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 180, in _execute_query
                                                result = cursor.execute(query)
                                            OperationalError: no such column: None
                                            -->End of Python script error report<--
2021-01-15 11:59:10.468 T:13149908992   ERROR: GetDirectory - Error getting plugin://plugin.video.seren/?action=showsPopularRecent&from_widget=false
2021-01-15 11:59:10.496 T:8746814976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=showsPopularRecent&from_widget=false) failed

**Comment by nixgates** [comment]
@queensryche6 could I ask you to provide a full log (not a snippet like above). While creating the log, please include all the failing endpoints. I suspect something is broken centrally in your install as they are all working from my testing.

**Comment by queensryche6** [comment]
After an update (.13 or.14 can't remember exactly) everything is working again. Thanks again for your efforts!
