### ISSUE TITLE
[BUG] Seren 2.0.12 can't pull new TV show event with trakt authenticate

### ISSUE THREAD

**Issue by minhgi** [nixgates/plugin.video.seren#423]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**
Seren 2.0.12 can't pull new TV show event with trakt authenticate.

**To Reproduce**

**Expected behavior**
Choosing new tv show should  newly released tv show.  Was working prior with 2.0.10

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9]
 - Version [Seren 2.0.12]

**Additional context**

**Comment by nixgates** [comment]
@minhgi going to need a debug log to assist with this one

**Comment by jweinr** [comment]
> @minhgi going to need a debug log to assist with this one

Here you go mate, it's the same for me, New TV Shows not list not loading.

https://paste.kodi.tv/agefupowow.kodi

**Comment by highrollar420** [comment]
I am also getting this error. Plus it is taking Trakt to sync forever a good 15-20 minutes. Sorry to jump on your thread.

**Comment by SoreTissue** [comment]
Since Seren 2.0.10 New Tv Shows populates for me but shows duplcates of shows. Theres usually at least 3 shows it shows twice.
I've seen this on multiple setups and on different networks. Btw thx for all your hard work Nixgates.

Nvidia Shield
Kodi 18.9
Seren 2.0.12
It was a clean install when seren 2.0.6 was released
Running Artic Horizon Skin
Seen same issue on Auramod and default skin
Also seen on Windows 10

To reproduce:
open seren app 
go to discover tv shows
go to New Tv Shows.
See duplicates.

Tried clearing, cache, all metadata, resyncing trakt

debug log file:
https://paste.kodi.tv/banexowami.kodi

**Comment by nixgates** [comment]
@SoreTissue please note the duplicates are due to the items returned from Trakt, not a fault of Seren.

@jweinr there's no errors in your log, can you try clear cache and pull the list again? This menu is working for myself.

**Comment by jweinr** [comment]
Still errors on 2.0.13

https://paste.kodi.tv/deyimemoyi.kodi

Cleaned cache, reset database and reset trakt auth.
Hopefully this log helps you

**Comment by nixgates** [comment]
@jweinr that looks like a trakt time out. Couldn't talk to the server. Perhaps you can try again after a bit?

**Comment by nixgates** [comment]
Closing this off, no longer reproducible on my end and no one seems to be replying. 

Let me know if this is still an issue and I'll re-open it.

**Comment by minhgi** [comment]
Sorry. I thought this was still being work on.  I update seren to 2.0.15 and still having issue with. I have reinstall Seren on fresh Kodi and get this error.

2021-01-21 11:33:00.667 T:15356   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.RetryError'>
                                            Error Contents: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /calendars/all/shows/new/23-12-2020/30?languages=%2Cen&extended=full (Caused by ResponseError('too many 500 error responses',))
                                            Traceback (most recent call last):
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 19, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\router.py", line 476, in dispatch
                                                tvshowMenus.Menus().shows_new()
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\gui\tvshowMenus.py", line 301, in shows_new
                                                extended="full",
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\trakt.py", line 596, in get_json
                                                response = self.get(url=url, **params)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\trakt.py", line 121, in wrapper
                                                response = func(*args, **kwargs)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\trakt.py", line 576, in get
                                                timeout=timeout,
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\minhg\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 507, in send
                                                raise RetryError(e, request=request)
                                            RetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /calendars/all/shows/new/23-12-2020/30?languages=%2Cen&extended=full (Caused by ResponseError('too many 500 error responses',))
                                            -->End of Python script error report<--

**Comment by minhgi** [comment]
With or without Trakt, same error message.  Why is it trying to pull old new TV show from 12/23/2020 calendar??????

RetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /calendars/all/shows/new/23-12-2020/30?languages=%2Cen&extended=full (Caused by ResponseError('too many 500 error responses',))
