### ISSUE TITLE
[BUG] Crash while watching movies/tv shows

### ISSUE THREAD

**Issue by dimovskidamjan** [nixgates/plugin.video.seren#431]
**Logs**

```
2021-01-16 22:11:56.835 T:1235210464  NOTICE: SEREN: a4kScrapers.movie.piratebay: took 7279 ms
2021-01-16 22:11:57.309 T:1251995872  NOTICE: SEREN: a4kScrapers.movie.torrentz2: 7
2021-01-16 22:11:57.310 T:1251995872  NOTICE: SEREN: a4kScrapers.movie.torrentz2: took 6901 ms
2021-01-16 22:11:58.942 T:1126166752  NOTICE: SEREN: a4kScrapers.movie.yts: 4
2021-01-16 22:11:58.943 T:1126166752  NOTICE: SEREN: a4kScrapers.movie.yts: took 3693 ms
2021-01-16 22:11:58.967 T:1059025120  NOTICE: SEREN: a4kScrapers.movie.scenerls: 2
2021-01-16 22:11:58.967 T:1059025120  NOTICE: SEREN: a4kScrapers.movie.scenerls: took 6427 ms
2021-01-16 22:11:59.141 T:1201639648  NOTICE: SEREN: a4kScrapers.movie.torrentapi: 0
2021-01-16 22:11:59.141 T:1201639648  NOTICE: SEREN: a4kScrapers.movie.torrentapi: took 4190 ms
2021-01-16 22:11:59.327 T:1599262944  NOTICE: SEREN: a4kScrapers.movie.magnetdl: 39
2021-01-16 22:11:59.328 T:1599262944  NOTICE: SEREN: a4kScrapers.movie.magnetdl: took 7458 ms
2021-01-16 22:11:59.769 T:1092595936  NOTICE: SEREN: a4kScrapers.movie.skytorrents: 2
2021-01-16 22:11:59.769 T:1092595936  NOTICE: SEREN: a4kScrapers.movie.skytorrents: took 4330 ms
2021-01-16 22:11:59.949 T:1226817760  NOTICE: SEREN: a4kScrapers.movie.lime: 38
2021-01-16 22:11:59.949 T:1226817760  NOTICE: SEREN: a4kScrapers.movie.lime: took 8076 ms
2021-01-16 22:12:00.203 T:1320935648  NOTICE: SEREN: a4kScrapers.movie.solidtorrents: 19
2021-01-16 22:12:00.203 T:1320935648  NOTICE: SEREN: a4kScrapers.movie.solidtorrents: took 8337 ms
2021-01-16 22:12:00.414 T:1117774048  NOTICE: SEREN: a4kScrapers.movie.nyaa: 0
2021-01-16 22:12:00.414 T:1117774048  NOTICE: SEREN: a4kScrapers.movie.nyaa: took 4888 ms
2021-01-16 22:12:00.428 T:1109381344  NOTICE: SEREN: a4kScrapers.movie.zooqle: 2
2021-01-16 22:12:00.428 T:1109381344  NOTICE: SEREN: a4kScrapers.movie.zooqle: took 4357 ms
2021-01-16 22:12:00.810 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.magnetdl cancellation requested
2021-01-16 22:12:00.810 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.cached cancellation requested
2021-01-16 22:12:00.810 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.lime cancellation requested
2021-01-16 22:12:00.810 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.bitlord cancellation requested
2021-01-16 22:12:00.810 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.movcr cancellation requested
2021-01-16 22:12:00.811 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.solidtorrents cancellation requested
2021-01-16 22:12:00.811 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.yts cancellation requested
2021-01-16 22:12:00.811 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.skytorrents cancellation requested
2021-01-16 22:12:00.811 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.kickass cancellation requested
2021-01-16 22:12:00.811 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.torrentgalaxy cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.torrentdownload cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.scenerls cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.zooqle cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.btdb cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.rlsbb cancellation requested
2021-01-16 22:12:00.812 T:1275060448  NOTICE: SEREN: a4kScrapers.movie.leet cancellation requested
2021-01-16 22:12:01.114 T:1067417824  NOTICE: SEREN: a4kScrapers.movie.torrentdownload: 19, 5 missing seeds info
2021-01-16 22:12:01.114 T:1067417824  NOTICE: SEREN: a4kScrapers.movie.torrentdownload: took 3856 ms
2021-01-16 22:12:01.376 T:1193246944  NOTICE: SEREN: a4kScrapers.movie.kickass: 0
2021-01-16 22:12:01.376 T:1193246944  NOTICE: SEREN: a4kScrapers.movie.kickass: took 9260 ms
2021-01-16 22:12:01.422 T:1266667744  NOTICE: SEREN: a4kScrapers.movie.cached: 188
2021-01-16 22:12:01.423 T:1266667744  NOTICE: SEREN: a4kScrapers.movie.cached: took 11004 ms
2021-01-16 22:12:01.575 T:1168109792   ERROR: SEREN: None
2021-01-16 22:12:01.575 T:1168109792   ERROR: SEREN: None
                                             
                                            Pre-emptive termination has stopped this request
2021-01-16 22:12:01.615 T:1168109792  NOTICE: SEREN: https://bitlordsearch.com/get_list failed - Traceback (most recent call last):
                                              File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 163, in _request_core
                                                response = request(None)
                                            PreemptiveCancellation
2021-01-16 22:12:02.402 T:1310716128  NOTICE: SEREN: a4kScrapers.movie.leet: 0
2021-01-16 22:12:02.403 T:1310716128  NOTICE: SEREN: a4kScrapers.movie.leet: took 5105 ms
2021-01-16 22:12:02.420 T:1075810528  NOTICE: SEREN: a4kScrapers.movie.btdb: 0
2021-01-16 22:12:02.420 T:1075810528  NOTICE: SEREN: a4kScrapers.movie.btdb: took 6343 ms
2021-01-16 22:12:02.850 T:1293152480  NOTICE: SEREN: a4kScrapers.movie.movcr: 0
2021-01-16 22:12:02.850 T:1293152480  NOTICE: SEREN: a4kScrapers.movie.movcr: took 12440 ms
2021-01-16 22:12:03.043 T:1168109792   ERROR: SEREN: None
2021-01-16 22:12:03.043 T:1168109792   ERROR: SEREN: None
                                             
                                            Pre-emptive termination has stopped this request
2021-01-16 22:12:03.044 T:1168109792  NOTICE: SEREN: https://bitlordsearch.com/get_list failed - Traceback (most recent call last):
                                              File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 163, in _request_core
                                                response = request(None)
                                            PreemptiveCancellation
2021-01-16 22:12:03.044 T:1168109792   ERROR: Traceback (most recent call last):
2021-01-16 22:12:03.045 T:1168109792   ERROR:   File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/core.py", line 417, in _search_core
2021-01-16 22:12:03.045 T:1168109792   ERROR:     response = self._search_request(url, query)
2021-01-16 22:12:03.045 T:1168109792   ERROR:   File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/torrent/bitlord.py", line 50, in _search_request
2021-01-16 22:12:03.045 T:1168109792   ERROR:     return self._search_request(url, query, force_token_refresh=True)
2021-01-16 22:12:03.045 T:1168109792   ERROR:   File "/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/providers/a4kScrapers/en/torrent/bitlord.py", line 51, in _search_request
2021-01-16 22:12:03.045 T:1168109792   ERROR:     core.tools.log('No response from %s' %url, 'error')
2021-01-16 22:12:03.045 T:1168109792   ERROR: TypeError: not all arguments converted during string formatting
2021-01-16 22:12:03.046 T:1210032352  NOTICE: SEREN: a4kScrapers.movie.bitlord: 0
2021-01-16 22:12:03.046 T:1210032352  NOTICE: SEREN: a4kScrapers.movie.bitlord: took 8975 ms
2021-01-16 22:12:03.950 T:1084203232  NOTICE: SEREN: a4kScrapers.movie.torrentgalaxy: 0
2021-01-16 22:12:03.950 T:1084203232  NOTICE: SEREN: a4kScrapers.movie.torrentgalaxy: took 6618 ms
2021-01-16 22:12:03.973 T:1210032352 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2021-01-16 22:12:03.973 T:1210032352  NOTICE: LoadJpeg: unable to load special://skin/extras/backgrounds/default.jpg
2021-01-16 22:12:08.308 T:1210032352 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2021-01-16 22:12:08.308 T:1210032352  NOTICE: LoadJpeg: unable to load special://skin/extras/backgrounds/default.jpg
2021-01-16 22:12:11.320 T:1210032352 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2021-01-16 22:12:11.320 T:1210032352  NOTICE: LoadJpeg: unable to load special://skin/extras/backgrounds/default.jpg
2021-01-16 22:12:12.242 T:1916404656  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520259514%257D&from_widget=true
2021-01-16 22:12:12.454 T:1320935648  NOTICE: Creating InputStream
2021-01-16 22:12:13.094 T:1320935648  NOTICE: Creating Demuxer
2021-01-16 22:12:14.096 T:1320935648  NOTICE: Opening stream: 0 source: 256
2021-01-16 22:12:14.096 T:1320935648  NOTICE: Creating video codec with codec id: 27
2021-01-16 22:12:14.111 T:1320935648  NOTICE: Creating video thread
2021-01-16 22:12:14.146 T:1218425056  NOTICE: running thread: video_thread
2021-01-16 22:12:14.316 T:1320935648  NOTICE: Opening stream: 1 source: 256
2021-01-16 22:12:14.317 T:1320935648  NOTICE: Finding audio codec for: 86020
2021-01-16 22:12:14.319 T:1320935648  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder dca
2021-01-16 22:12:14.320 T:1320935648  NOTICE: Creating audio thread
2021-01-16 22:12:14.320 T:1493561568  NOTICE: running thread: CVideoPlayerAudio::Process()
2021-01-16 22:12:14.321 T:1320935648  NOTICE: Opening stream: 2 source: 256
2021-01-16 22:12:14.346 T:1493561568  NOTICE: Creating audio stream (codec id: 86020, channels: 6, sample rate: 48000, no pass-through)
2021-01-16 22:12:15.459 T:1218425056 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-16 22:12:16.293 T:1218425056 WARNING: CRenderManager::AddVideoPicture - timeout waiting for render
2021-01-16 22:12:19.481 T:1493561568   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2021-01-16 22:12:38.788 T:1275060448   ERROR: Previous line repeats 1 times.
2021-01-16 22:12:38.788 T:1275060448   ERROR: SEREN: Trakt returned a 429 (Rate Limit Exceeded): while requesting https://api.trakt.tv/scrobble/start
2021-01-16 22:12:42.605 T:1493561568   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2021-01-16 22:12:44.851 T:1275060448   ERROR: SEREN: Trakt returned a 429 (Rate Limit Exceeded): while requesting https://api.trakt.tv/scrobble/start
2021-01-16 22:12:49.558 T:1218425056 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-16 22:13:06.896 T:1493561568  NOTICE: CActiveAEStream::AddData - messy timestamps, increasing interval for measuring average error to 6000 ms
2021-01-16 22:14:20.214 T:1218425056 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

**Describe the bug**
Whole Kodi crashed while watching a movie on Seren. This happens intermittently, and is not related to a particular movie or show.

**To Reproduce**
I cannot consistently reproduce the error, just have to watch movies and tv show until it happens, but it happens multiple times per movie for example, like 2-3 crashes during a normal movie.

**Kodi Version (please complete the following information):**
 - Kodi Version OSMC November 2020 2020.11-1
 - Seren Version 2.0.12

**Comment by nixgates** [comment]
If you're experiencing crashes, this is due the reuselanguageinvoker setting from Kodi. you can disable this in the shortcuts section of Seren's setting window.
