### ISSUE TITLE
[BUG] python3 sorting error on play

### ISSUE THREAD

**Issue by hurricane-dorian** [nixgates/plugin.video.seren#443]
Kodi 19-Rc1
Seren 2.0.13
Python 3.9.1
When trying to play or list sources

INFO <general>: SEREN: Seren, Running Path - {'action': 'getSources', 'action_args': {'mediatype': 'episode', 'trakt_id': 4540222, 'trakt_season_id': 231823, 'trakt_show_id': 144121}, 'from_widget': 'false'}
  INFO <general>: Loading skin file: /home/dorian/.kodi/addons/plugin.video.seren/resources/skins/Default/1080i/persistent_background.xml, load type: LOAD_ON_GUI_INIT
 ERROR <general>: SEREN: ^(?:your\ honor)+(?:2020 )? ?(?:s0?1e0?1(?: |e\d\d?)|season\ 0?1\ episode\ 0?1)+
  INFO <general>: SEREN: Pre-emptively Terminated
 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
       Error Type: <class 'TypeError'>
       Error Contents: cannot pickle 'dict_values' object
       Traceback (most recent call last):
         File "/home/dorian/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
           router.dispatch(g.REQUEST_PARAMS)
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 146, in dispatch
           sources = helpers.SourcesHelper().get_sources(
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 468, in _decorated
           fresh_result = func(*args, **kwargs)
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/modules/helpers.py", line 57, in get_sources
           sources = Sources(item_information).get_sources()
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/modules/getSources.py", line 111, in get_sources
           return self._finalise_results()
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/modules/getSources.py", line 223, in _finalise_results
           sorted_sources = SourceSorter(self.media_type).sort_sources(
         File "/home/dorian/.kodi/addons/plugin.video.seren/resources/lib/modules/source_sorter.py", line 247, in sort_sources
           self.torrent_list = deepcopy(torrents)
         File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
           rv = reductor(4)
       TypeError: cannot pickle 'dict_values' object
       -->End of Python script error report<--

**Comment by nixgates** [comment]
@hurricane-dorian thanks, I'll have this fixed up for next update :+1:

**Comment by nixgates** [comment]
@hurricane-dorian fixed awaiting update :)

**Comment by nixgates** [comment]
Update released, closing it off :)
