### ISSUE TITLE
[BUG] Playing Movies like Chick Fight in Seren give an error

### ISSUE THREAD

**Issue by Ebonlore** [nixgates/plugin.video.seren#465]
Kodi 18.9 64 bit Shield Pro Seren 2.0.16 Real Debrid/Premiumize

2021-01-23 11:26:17.491 T:30488 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520107417%257D&from_widget=false
2021-01-23 11:26:17.491 T:30488   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520107417%257D&from_widget=false
2021-01-23 11:26:17.494 T:30520 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520147669%257D&from_widget=false
2021-01-23 11:26:17.495 T:30520   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520147669%257D&from_widget=false
2021-01-23 11:26:19.808 T:32482   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 117, in dispatch
                                                item_information = tools.get_item_information(action_args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/tools.py", line 276, in get_item_information
                                                movies.TraktSyncDatabase().get_movie(action_args["trakt_id"])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/movies.py", line 121, in get_movie
                                                )[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-23 11:26:20.269 T:18171   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520526974%257D&from_widget=false]
2021-01-23 11:26:20.282 T:30497 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520107417%257D&from_widget=false
2021-01-23 11:26:20.282 T:30497   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520107417%257D&from_widget=false
2021-01-23 11:26:20.285 T:30488 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520147669%257D&from_widget=false
2021-01-23 11:26:20.285 T:30488   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=getSources&action_args=%257B%2522mediatype%2522%253A%2520%2522movie%2522%252C%2520%2522trakt_id%2522%253A%2520147669%257D&from_widget=false

**Comment by nixgates** [comment]
@Ebonlore could please provide the full log. 

A snippet like this is hard to read and doesn't provide all the information required unfortunately.

**Comment by nixgates** [comment]
Closing this off as I still haven't received a log.

Let me know when and if you get the time to provide one and I'll re-opn this issue
