### ISSUE TITLE
[BUG] Seren Video Playback Fails and Freezes Kodi or Drops Back to Main

### ISSUE THREAD

**Issue by moderntrader** [nixgates/plugin.video.seren#468]
**Logs**
2021-01-24 00:16:52.618 T:7550   ERROR: EXCEPTION: XBMC is not playing any media file
2021-01-24 00:16:52.622 T:7550   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 194, in dispatch
                                                stream_link, item_information, resume_time=resume_time
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/player.py", line 105, in play_source
                                                self._keep_alive()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/player.py", line 571, in _keep_alive
                                                self._update_progress()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/player.py", line 418, in _update_progress
                                                self.current_time = self.getTime()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/player.py", line 126, in getTime
                                                return xbmc.Player().getTime()
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--

2021-01-24 04:42:47.428 T:24670   ERROR: SEREN: None
                                             
                                            bad_token
2021-01-24 04:42:47.439 T:24670   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.modules.exceptions.FailureAtRemoteParty'>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 356, in dispatch
                                                CacheAssistHelper().auto_cache(action_args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/cacheAssist.py", line 461, in auto_cache
                                                debrid_class.status_update_loop()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/cacheAssist.py", line 180, in status_update_loop
                                                raise e
                                            FailureAtRemoteParty
                                            -->End of Python script error report<--

Here is the complete log http://paste.kodi.tv/ebuzotetiw

**Describe the bug**
After playing a few episodes the playback fails or freezes forcing me to either back out of clip to kodi or restart device. I tend to click play next episode or allow it to begin on its own. I pause video some times but have turned off sleep and screensaver completely. 

**To Reproduce**
Don't have an exact method of constant reproduction but has happened with different video codec and resolutions

**Expected behavior**

**Kodi Version (please complete the following information):**

Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Android ARM 32-bit a Firestick that has been rooted and debloated to have additional ram available for kodi use

**Comment by nixgates** [comment]
`2021-01-24 00:16:52.502 T:7571  NOTICE: CVideoPlayer::OnExit()
2021-01-24 00:16:52.502 T:7571  NOTICE: VideoPlayer: eof, waiting for queues to empty
2021-01-24 00:16:52.503 T:7571  NOTICE: Closing stream player 1
2021-01-24 00:16:52.503 T:7571  NOTICE: Waiting for audio thread to exit
2021-01-24 00:16:52.508 T:7651  NOTICE: thread end: CVideoPlayerAudio::OnExit()`

As you might be able to see above, Kodi is dropping the playback of the item. This is unfortunately not something that's fixable from within Seren. 

Generally this is caused when Kodi believes the file is no longer streamable or has dropped out.

I would suggest testing with a blank advancedsettings.xml if any of those settings are set. 
Try lowering your max file sizes
Try changing CDN with your debrid provider

Unfortunately, there's nothing to fix from Seren's side of things with this issue.
