### ISSUE TITLE
[BUG] Unable to perform search in Seren / Kodi 19 with error "SEREN: NoneType: None"

### ISSUE THREAD

**Issue by sabatale** [nixgates/plugin.video.seren#548]
**Logs**

**SEREN: NoneType: None**

```
2021-03-10 19:34:26.272 T:11547    INFO <general>: CAndroidUtils: SetNativeResolution: 20: 1920x1080 3840x2160@59.940060
2021-03-10 19:34:26.304 T:11547    INFO <general>: GL_VENDOR = NVIDIA Corporation
2021-03-10 19:34:26.305 T:11547    INFO <general>: GL_RENDERER = NVIDIA Tegra
2021-03-10 19:34:26.305 T:11547    INFO <general>: GL_VERSION = OpenGL ES 3.2 NVIDIA 418.00
2021-03-10 19:34:26.305 T:11547    INFO <general>: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20
2021-03-10 19:34:26.305 T:11547    INFO <general>: GL_EXTENSIONS = GL_EXT_debug_marker GL_EXT_base_instance GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clear_texture GL_EXT_clip_control GL_EXT_clip_cull_distance GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_debug_label GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_EGL_image_array GL_EXT_EGL_image_storage GL_EXT_EGL_image_external_wrap_modes GL_EXT_external_buffer GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_map_buffer_range GL_EXT_multi_draw_indirect GL_EXT_multisample_compatibility GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_primitive_bounding_box GL_EXT_protected_textures GL_EXT_raster_multisample GL_EXT_render_snorm GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sparse_texture GL_EXT_sparse_texture2 GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_format_BGRA8888 GL_EXT_texture_mirror_clamp_to_edge GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_view GL_EXT_draw_transform_feedback GL_EXT_unpack_subimage GL_EXT_window_rectangles GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_NV_bgr GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_conditional_render GL_NV_conservative_raster GL_NV_copy_buffer GL_NV_copy_image GL_NV_draw_buffers GL_NV_draw_instanced GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_EGL_stream_consumer_external GL_NV_explicit_attrib_location GL_NV_fbo_color_attachments GL_NV_fill_rectangle GL_NV_fragment_coverage_to_color GL_NV_fragment_shader_interlock GL_NV_framebuffer_blit GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample GL_NV_generate_mipmap_sRGB GL_NV_geometry_shader_passthrough GL_NV_instanced_arrays GL_NV_internalformat_sample_query GL_NV_gpu_shader5 GL_NV_image_formats GL_NV_occlusion_query_samples GL_NV_non_square_matrices GL_NV_pack_subimage GL_NV_packed_float GL_NV_packed_float_linear GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_pixel_buffer_object GL_NV_polygon_mode GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_secure_context GL_NV_shader_atomic_fp16_vector GL_NV_shader_noperspective_interpolation GL_NV_shadow_samplers_array GL_NV_shadow_samplers_cube GL_NV_sRGB_formats GL_NV_texture_array GL_NV_texture_barrier GL_NV_texture_border_clamp GL_NV_texture_compression_latc GL_NV_texture_compression_s3tc GL_NV_texture_compression_s3tc_update GL_NV_timer_query GL_NV_viewport_array GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_depth24 GL_OES_depth32 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_buffer GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_gpu_shader5 GL_OES_shader_io_blocks GL_OES_texture_view GL_OES_primitive_bounding_box GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_cube_map_array GL_OES_texture_npot GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OES_viewport_array GL_OVR_multiview GL_OVR_multiview2 GL_ANDROID_extension_pack_es31a 
2021-03-10 19:34:27.789 T:12467    INFO <general>: initializing python engine.
2021-03-10 19:34:28.232 T:12467 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-10 19:34:28.671 T:12467    INFO <general>: Skipped 16 duplicate messages..
2021-03-10 19:34:28.671 T:12467    INFO <general>: SEREN: Seren, Running Path - {'action': 'showsSearch', 'from_widget': 'false'}
2021-03-10 19:34:28.772 T:12469    INFO <general>: initializing python engine.
2021-03-10 19:34:29.462 T:12469 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-10 19:34:29.478 T:12469    INFO <general>: CPythonInvoker(33, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2021-03-10 19:34:30.169 T:12469    INFO <general>: Python interpreter stopped
2021-03-10 19:34:33.771 T:12478    INFO <general>: initializing python engine.
2021-03-10 19:34:34.495 T:12478 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-10 19:34:34.550 T:12478    INFO <general>: Skipped 1 duplicate messages..
2021-03-10 19:34:34.550 T:12478    INFO <general>: CPythonInvoker(34, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2021-03-10 19:34:35.304 T:12478    INFO <general>: Python interpreter stopped
2021-03-10 19:34:36.109 T:12467    INFO <general>: SEREN: Inserting Shows into sync database: 10
2021-03-10 19:34:37.032 T:12534   ERROR <general>: SEREN: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1162, in _get_series_cast
                                                       "cast": self._handle_cast(self.get_json("series/{}/actors".format(tvdb_id)))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 942, in get_json
                                                       return self._handle_response(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/apibase.py", line 29, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 980, in _handle_response
                                                       item = self._try_detect_type(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1003, in _try_detect_type
                                                       if "airedSeasons" in item or "seriesName" in item:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   
2021-03-10 19:34:37.039 T:12486    INFO <general>: SEREN: Inserting seasons into sync database: 31
2021-03-10 19:34:37.142 T:12500   ERROR <general>: SEREN: NoneType: None
                                                   
2021-03-10 19:34:37.147 T:12500   ERROR <general>: SEREN: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 565, in update
                                                       self._update_tvshow(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 696, in _update_tvshow
                                                       self._update_tvshow_fallback(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 774, in _update_tvshow_fallback
                                                       db_object, self.tvdb_api.get_show(db_object["tvdb_id"])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 70, in wrapper
                                                       return {"tvdb_object": tvdb_art_sorter(func(*args, **kwarg))}
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1080, in get_show
                                                       item = tools.smart_merge_dictionary(item, thread_pool.wait_completion())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1162, in _get_series_cast
                                                       "cast": self._handle_cast(self.get_json("series/{}/actors".format(tvdb_id)))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 942, in get_json
                                                       return self._handle_response(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/apibase.py", line 29, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 980, in _handle_response
                                                       item = self._try_detect_type(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1003, in _try_detect_type
                                                       if "airedSeasons" in item or "seriesName" in item:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   
2021-03-10 19:34:37.174 T:12486    INFO <general>: SEREN: Inserting episodes into sync database: 0
2021-03-10 19:34:37.379 T:12485   ERROR <general>: SEREN: NoneType: None
                                                   
2021-03-10 19:34:37.383 T:12485   ERROR <general>: SEREN: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 38, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 519, in _update_shows
                                                       updated_items = self._update_objects(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 454, in _update_objects
                                                       updated_items = self.task_queue.wait_completion()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 565, in update
                                                       self._update_tvshow(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 696, in _update_tvshow
                                                       self._update_tvshow_fallback(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 774, in _update_tvshow_fallback
                                                       db_object, self.tvdb_api.get_show(db_object["tvdb_id"])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 70, in wrapper
                                                       return {"tvdb_object": tvdb_art_sorter(func(*args, **kwarg))}
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1080, in get_show
                                                       item = tools.smart_merge_dictionary(item, thread_pool.wait_completion())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1162, in _get_series_cast
                                                       "cast": self._handle_cast(self.get_json("series/{}/actors".format(tvdb_id)))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 942, in get_json
                                                       return self._handle_response(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/apibase.py", line 29, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 980, in _handle_response
                                                       item = self._try_detect_type(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1003, in _try_detect_type
                                                       if "airedSeasons" in item or "seriesName" in item:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   
2021-03-10 19:34:37.383 T:12467   ERROR <general>: SEREN: NoneType: None
                                                   
2021-03-10 19:34:37.391 T:12467   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 290, in dispatch
                                                       tvshowMenus.Menus().shows_search(action_args)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 416, in shows_search
                                                       self.shows_search_results(query)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 429, in shows_search_results
                                                       self.list_builder.show_list_builder(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 99, in show_list_builder
                                                       shows.TraktSyncDatabase().get_show_list(trakt_list, **params),
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 240, in get_show_list
                                                       self._update_mill_format_shows(trakt_list, False)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 559, in _update_mill_format_shows
                                                       self.parent_task_queue.wait_completion()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 38, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 519, in _update_shows
                                                       updated_items = self._update_objects(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 454, in _update_objects
                                                       updated_items = self.task_queue.wait_completion()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 565, in update
                                                       self._update_tvshow(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 696, in _update_tvshow
                                                       self._update_tvshow_fallback(db_object)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/metadataHandler.py", line 774, in _update_tvshow_fallback
                                                       db_object, self.tvdb_api.get_show(db_object["tvdb_id"])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 70, in wrapper
                                                       return {"tvdb_object": tvdb_art_sorter(func(*args, **kwarg))}
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1080, in get_show
                                                       item = tools.smart_merge_dictionary(item, thread_pool.wait_completion())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 197, in wait_completion
                                                       self._try_raise()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 207, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1162, in _get_series_cast
                                                       "cast": self._handle_cast(self.get_json("series/{}/actors".format(tvdb_id)))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 942, in get_json
                                                       return self._handle_response(
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/apibase.py", line 29, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 980, in _handle_response
                                                       item = self._try_detect_type(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/indexers/tvdb.py", line 1003, in _try_detect_type
                                                       if "airedSeasons" in item or "seriesName" in item:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
                                                   
2021-03-10 19:34:38.140 T:12467 WARNING <general>: CPythonInvoker(32, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc8PlayListE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon4xbmc7MonitorE
2021-03-10 19:34:38.141 T:12467    INFO <general>: Python interpreter stopped
2021-03-10 19:34:38.141 T:12464   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.seren/?action=showsSearch&from_widget=false
2021-03-10 19:34:38.154 T:11547   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=showsSearch&from_widget=false) failed
```

**Describe the bug**
When trying to perform any search, no results are returned and the "Seren error" notification gets displayed.

**To Reproduce**
1. Go to Search.
2. Search for any keyword.
3. No results.

**Expected behavior**
Results should be returned.

**Kodi Version (please complete the following information):**
 - Kodi 19.0
 - Latest Seren
 - Latest Arctic Horizon skin
 - Shield Pro 2019

**Comment by drinfernoo** [comment]
Closed as #549 has provided a better log and more information for the same issue.
