### ISSUE TITLE
[BUG] Certain shows in trakt collection causes seren to crash when loading collection

### ISSUE THREAD

**Issue by kjp949** [nixgates/plugin.video.seren#569]
**Logs**

    2021-03-18 21:25:29.543 T:3241206592   DEBUG: SEREN: Media type: tvshow
    2021-03-18 21:25:29.543 T:3241206592   DEBUG: SEREN: Converting TV Info Dates to local time for display
    2021-03-18 21:25:29.545 T:3241206592   DEBUG: SEREN: Original utc_string: 2016-06-13T02:00:00  local_time: 2016-06-12T20:00:00
    2021-03-18 21:25:29.547 T:3241206592   DEBUG: SEREN: Original utc_string: 2021-01-27T20:01:41  local_time: 2021-01-27T14:01:41
    2021-03-18 21:25:29.550 T:3241206592   DEBUG: SEREN: Original utc_string: 2016-06-13T02:00:00  local_time: 2016-06-12T20:00:00
    2021-03-18 21:25:29.551 T:3241206592   ERROR: EXCEPTION: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
    2021-03-18 21:25:29.557 T:3241206592   ERROR: SEREN: Traceback (most recent call last):
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 163, in _common_menu_builder
                                                    if item is not None
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 1111, in add_directory_item
                                                    item.setInfo("video", info)
                                                TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
    2021-03-18 21:25:29.558 T:3241206592 WARNING: Attempt to use invalid handle 1
    2021-03-18 21:25:29.558 T:3216028480 WARNING: Previous line repeats 2 times.
    2021-03-18 21:25:29.558 T:3216028480   DEBUG: Thread waiting 3216028480 terminating
    2021-03-18 21:25:29.560 T:3241206592   DEBUG: SEREN: Processing Time -   1193ms - showsMyCollection
    2021-03-18 21:25:29.569 T:3241206592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.TypeError'>
                                                Error Contents: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                                Traceback (most recent call last):
                                                  File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
                                                    router.dispatch(g.REQUEST_PARAMS)
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 260, in dispatch
                                                    tvshowMenus.Menus().my_shows_collection()
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 73, in wrapper
                                                    return func(*args, **kwargs)
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 263, in my_shows_collection
                                                    self.list_builder.show_list_builder(trakt_list, no_paging=no_paging, sort=sort)
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 102, in show_list_builder
                                                    **params
                                                  File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 176, in _common_menu_builder
                                                    raise e
                                                TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                                -->End of Python script error report<--
    2021-03-18 21:25:29.569 T:3241206592   DEBUG: onExecutionDone(12, /storage/.kodi/addons/plugin.video.seren/seren.py)
    2021-03-18 21:25:29.571 T:4090007568   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
    2021-03-18 21:25:29.593 T:3271557952   DEBUG: Thread BackgroundLoader start, auto delete: false
    2021-03-18 21:25:29.614 T:3271557952   DEBUG: Thread BackgroundLoader 3271557952 terminating
    2021-03-18 21:25:29.621 T:4090007568    INFO: CheckIdle - Closing session to http://folder.jpg (easy=0xe6a29328, multi=(nil))
    2021-03-18 21:25:29.622 T:4090007568   DEBUG: ------ Window Init (DialogNotification.xml) ------
    2021-03-18 21:25:29.853 T:3241206592    INFO: Python interpreter stopped
    2021-03-18 21:25:29.853 T:3241206592    INFO: Previous line repeats 3 times.
    2021-03-18 21:25:29.853 T:3241206592   DEBUG: Thread LanguageInvoker 3241206592 terminating
    2021-03-18 21:25:35.028 T:4090007568   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Describe the bug**
Seren will crash with the errors posted above when certain shows are in your trakt collection and you go to browse your collection.  This error is from the show "Ghosts of Shepherdstown".  https://www.themoviedb.org/search/tv?query=Ghosts%20of%20Shepherdstown  2 shows show up on TMDB and I think this is causing seren to crash.  Another show like "Chopped After Hours" also caused seren to crash.  That show isn't even listed on TMDB.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version Kodi (18.9 (18.9.0) Git:00ff7594e42e9539912c9bd12c5a6a9d1b9d8d78). Platform: Linux ARM 32-bit
 - Seren 2.0.17 - happened in previous versions too.

**Additional context**

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
