### ISSUE TITLE
[BUG] Show isn't showing all the episodes in tvdb, causing playing to fail

### ISSUE THREAD

**Issue by dandidums** [nixgates/plugin.video.seren#592]
**Logs**

```
2021-04-04 14:55:11.160 T:9942  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.container.router - Attempting to play item
                                            {u'info': u'play', u'tmdb_type': u'tv', u'episode': u'14', u'tmdb_id': u'49009', u'season': u'8', u'ignore_default': u'true'}
2021-04-04 14:55:23.816 T:9942  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - playing path with xbmc.Player()
                                            plugin://plugin.video.seren/?action=getSources&forceresumecheck=true&source_select=true&actionArgs=%7B%22episode%22%3A%2014%2C%20%22item_type%22%3A%
20%22episode%22%2C%20%22season%22%3A%208%2C%20%22trakt_id%22%3A%2048702%7D
2021-04-04 14:55:27.089 T:10176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 16, in <module>
                                                g.init_globals(sys.argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 328, in init_gl
obals
                                                self.init_request(argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 438, in init_re
quest
                                                self.REQUEST_PARAMS["action_args"]
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 464, in legacy_
action_args_converter
                                                action_args["episode"],
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
```

**Describe the bug**
Seems for some reason The Goldbergs (2013) isn't showing up properly in the UI and due to above errors, is likely because of the API. Looking at the show in [TMDB](https://www.themoviedb.org/tv/49009-the-goldbergs/season/8/episode/13) (see season 8 episodes 14), it does have the relevant episodes.

**To Reproduce**
1. Find The Goldbergs (2013)
2. Open Season 8
3. Notice episodes 14 isn't in the list.
4. Use TMDB helper to go to The Goldbergs 2013 season 8
5. Play episode 14 or 15
6. Seren fails with an error, looking at the logs produces above error.

**Expected behavior**
It should show the released episodes, and play them.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version: 2.0.18

**Comment by nki2bpz** [comment]
I have been having this problem across multiple shows since 2.0.18. Somewhere behind the scenes either with trakt or tmdb there are allot of discrepancies in episode count. I've noticed the problem compounded for me when I have a show in my widget (added to library by openinfo)
I would say this was soley an issue with tvdb/tmdb/trakt but when choosing to play any of these shows with tempest they play fine.

**Comment by bdkbaik** [comment]
Same thing happen to me. New episode is not showing in the list. So I have clear add on data and it's showing the new episodes

**Comment by dandidums** [comment]
Found another one, American Dad.

Seems the shows are showing correctly on TVDB, TMDB, and Trakt. So I'm not sure where it is going wrong. For American Dad for example, season 18 isn't showing at all in Seren, but is showing up everywhere else.

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.0?

**Comment by nki2bpz** [comment]
I can't say I've seen it happening since 2.1 but I've only had about 8hrs of viewing time. (that I wasn't sleeping) I'm not the op though and never had logs to confirm

**Comment by drinfernoo** [comment]
I'm going to close this one now.

**Comment by dandidums** [comment]
@drinfernoo this issue seems to be back. Example show Robot Chicken.
```
2021-09-18 13:57:10.762 T:32328  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player.players -- successfully resolved dummy file
                                            /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/dummy.mp4
2021-09-18 13:57:11.018 T:32328  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - playing path with xbmc.Player()
                                            plugin://plugin.video.seren/?action=getSources&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%201%2C%20%22item_type%22%3A%20%22episode%22%2C%2
0%22season%22%3A%2011%2C%20%22trakt_id%22%3A%20707%7D
2021-09-18 13:57:14.894 T:32478   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 16, in <module>
                                                g.init_globals(sys.argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 344, in init_gl
obals
                                                self.init_request(argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 501, in init_re
quest
                                                self.REQUEST_PARAMS["action_args"]
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 527, in legacy_
action_args_converter
                                                action_args["episode"],
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
````
