### ISSUE TITLE
Startup error Seren - Windows 10 & Xbox Series X

### ISSUE THREAD

**Issue by brokentechie** [nixgates/plugin.video.seren#604]
Log:

2021-04-23 19:20:15.008 T:5220 WARNING: CAddonSettings[script.module.universal]: failed to parse old setting definition for "db_port" of type "integer"
2021-04-23 19:20:15.011 T:5220  NOTICE: Universal - An Addons Toolkit: -watchhistory- -Loading sqlite3 as DB engine version: 3.17.0
2021-04-23 19:20:15.034 T:5220  NOTICE: Universal - An Addons Toolkit: -watchhistory- -DELETE FROM watch_history WHERE lastwatched < '2021-04-03'
2021-04-23 19:20:15.118 T:13520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cursor() got an unexpected keyword argument 'dictionary'
                                            Traceback (most recent call last):
                                              File "C:\Users\andyr\AppData\Roaming\Kodi\addons\plugin.video.seren\service.py", line 41, in <module>
                                                g.clear_kodi_bookmarks()
                                              File "C:\Users\andyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 656, in clear_kodi_bookmarks
                                                with self.get_kodi_video_db_connection() as video_database:
                                              File "C:\Users\andyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\__init__.py", line 192, in __enter__
                                                self._cursor = self._create_cursor()
                                              File "C:\Users\andyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\__init__.py", line 333, in _create_cursor
                                                return self._connection.cursor(dictionary=True)
                                            TypeError: cursor() got an unexpected keyword argument 'dictionary'
                                            -->End of Python script error report<--
2021-04-23 19:20:15.235 T:13528  NOTICE: [ script.module.myaccounts ]  service stopped

On starting Kodi Seren reports the above error since 2.0.19 update. 

Happens on Xbox and Windows 10

Cleared cache, uninstall and reinstall etc, error remains

**Comment by drinfernoo** [comment]
Please attach a full log file. Believe it or not, there are pertinent things in there, hence why we ask for it 😉

**Comment by brokentechie** [comment]
Xxx

**Comment by drinfernoo** [comment]
Debug log is best.

That being said, it seems that there's an issue with your `advancedsettings.xml`... I'd recommend deleting/remaking it to make sure that it's valid.

**Comment by brokentechie** [comment]
Xxx

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.0?

**Comment by brokentechie** [comment]
Xxx
