### ISSUE TITLE
[BUG] Timezone error not loading any titles

### ISSUE THREAD

**Issue by matiasvelizb** [nixgates/plugin.video.seren#607]
**Logs**
https://paste.kodi.tv/zamagaxaru.kodi

**Describe the bug**
Seren allows me to navigate any menu normally, but after choosing a source of any type (movies / series) I get an error and no video playback at all. Aparently error seems to be related to my timezone, which is properlly set in my Windows 10 laptop (Chile UTC-4 Santiago)

**To Reproduce**
1. Play a movie / series from any list
2. Choose any source
3. See error

**Expected behavior**
Video playback after choosing a source, without changing my timezone in my laptop.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0.0
 - Seren Version 2.0.19

**Comment by drinfernoo** [comment]
Can you get a screenshot of what your timezone setting is in Windows?

**Comment by matiasvelizb** [comment]
> Can you get a screenshot of what your timezone setting is in Windows?

Sure, sorry for the spanish screenshot. I've tried setting the same timezone manually as well and no luck. Seren works fine in a raspberry pi with LibreELEC I've got though.

https://i.imgur.com/VK0UJSW.png

**Comment by satyrical** [comment]
I am getting this same error with a UTC -5 Eastern Time(US and Canada) but with daylight savings turned off (as I am in the Cayman Islands).

Getting this in the KODI log : 

`2021-04-30 15:49:45.963 T:27624   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: Timezone offset does not match system offset: -14400 != -18000. Please, check your config files.
                                                   Traceback (most recent call last):
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\router.py", line 272, in dispatch
                                                       tvshowMenus.Menus().my_show_progress()
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\trakt.py", line 71, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\gui\tvshowMenus.py", line 289, in my_show_progress
                                                       self.list_builder.show_list_builder(trakt_list, no_paging=no_paging, sort=sort)
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\list_builder.py", line 100, in show_list_builder
                                                       self._common_menu_builder(
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\list_builder.py", line 178, in _common_menu_builder
                                                       raise e
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\list_builder.py", line 154, in _common_menu_builder
                                                       list_items = [
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\list_builder.py", line 155, in <listcomp>
                                                       g.add_directory_item(
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 1159, in add_directory_item
                                                       self.convert_info_dates(info)
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 1197, in convert_info_dates
                                                       converted_dates = {key: tools.utc_to_local(info_dict.get(key))
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 1197, in <dictcomp>
                                                       converted_dates = {key: tools.utc_to_local(info_dict.get(key))
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\common\tools.py", line 627, in utc_to_local
                                                       local_tz = tzlocal.get_localzone()  # If this fails we should get UTC back
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\third_party\tzlocal\win32.py", line 133, in get_localzone
                                                       _cache_tz = _get_localzone()
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\third_party\tzlocal\win32.py", line 121, in _get_localzone
                                                       utils.assert_tz_offset(tz)
                                                     File "C:\Users\satyr\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\third_party\tzlocal\utils.py", line 46, in assert_tz_offset
                                                       raise ValueError(msg)
                                                   ValueError: Timezone offset does not match system offset: -14400 != -18000. Please, check your config files.
                                                   -->End of Python script error report<--`

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.0?

**Comment by matiasvelizb** [comment]
> Is this still an issue in 2.1.0?

Not an issue in a fresh install with Kodi 19.1
https://i.imgur.com/9b44diC.jpeg

Thanks
