### ISSUE TITLE
[BUG]Error when authorizing Real-Debrid

### ISSUE THREAD

**Issue by BTrailor** [nixgates/plugin.video.seren#609]
**Logs**

Please provide debug logs to assist with your issue

                                                   
2021-05-02 19:59:22.627 T:1186805   DEBUG <general>: CPythonInvoker(10, /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py): the source file to load is "/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py"
2021-05-02 19:59:22.628 T:1186805   DEBUG <general>: CPythonInvoker(10, /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py): setting the Python path to /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren:/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.youtube/resources/lib/:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.beautifulsoup4/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.certifi/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.chardet/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.future/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.idna/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.inputstreamhelper/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.myconnpy/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.requests/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.six/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.soupsieve/lib:/Users/btrailor/Library/Application Support/Kodi/addons/script.module.urllib3/lib:/Applications/Kodi.app/Contents/Libraries/lib/python3.8/site-packages/setuptools-18.4-py3.8.egg:/Applications/Kodi.app/Contents/Libraries/lib/python3.8/site-packages/Pillow-7.1.2-py3.8-macosx-10.14-x86_64.egg:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python38.zip:/Applications/Kodi.app/Contents/Libraries/lib/python3.8:/Applications/Kodi.app/Contents/Libraries/lib/python3.8/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python3.8/lib-dynload
2021-05-02 19:59:22.629 T:1186805   DEBUG <general>: CPythonInvoker(10, /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py): entering source directory /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren
2021-05-02 19:59:22.629 T:1186805   DEBUG <general>: CPythonInvoker(10, /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py): instantiating addon using automatically obtained id of "plugin.video.seren" dependent on version 3.0.0 of the xbmc.python api
2021-05-02 19:59:22.665 T:1184850    INFO <general>: SEREN: SETTINGS UPDATED
2021-05-02 19:59:22.679 T:1184850    INFO <general>: SEREN: FORCE REFRESHING WIDGETS
2021-05-02 19:59:22.739 T:1184548   DEBUG <general>: ------ Window Deinit (DialogAddonSettings.xml) ------
2021-05-02 19:59:22.792 T:1186805   DEBUG <CAddonSettings[plugin.video.seren]>: trying to load setting definitions from old format...
2021-05-02 19:59:23.135 T:1186805    INFO <general>: SEREN: Seren, Running Path - {'action': 'authRealDebrid'}
2021-05-02 19:59:26.831 T:1186805   DEBUG <general>: DialogProgress::Open called 
2021-05-02 19:59:26.833 T:1184548   DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2021-05-02 19:59:33.834 T:1186805   DEBUG <general>: SEREN: Processing Time -  10699ms - authRealDebrid
2021-05-02 19:59:33.834 T:1186805   DEBUG <general>: 
                                                   
2021-05-02 19:59:33.857 T:1186805   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 247, in dispatch
                                                       real_debrid.RealDebrid().auth()
                                                     File "/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 107, in auth
                                                       success = self._auth_loop()
                                                     File "/Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 61, in _auth_loop
                                                       response = self.session.get(url).json()
                                                     File "/Users/btrailor/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2021-05-02 19:59:33.867 T:1186805   DEBUG <general>: onExecutionDone(10, /Users/btrailor/Library/Application Support/Kodi/addons/plugin.video.seren/seren.py)
2021-05-02 19:59:33.867 T:1186805   DEBUG <general>: .
2021-05-02 19:59:33.883 T:1184548   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-05-02 19:59:34.009 T:1186805    INFO <general>: Python interpreter stopped
2021-05-02 19:59:34.009 T:1186805   DEBUG <general>: Thread LanguageInvoker 0x70000db5c000 terminating
2021-05-02 19:59:34.055 T:1184548   DEBUG <general>: ------ Window Deinit (DialogConfirm.xml) ------
2021-05-02 19:59:38.389 T:1184548   DEBUG <general>: ------ Window Init (Pointer.xml) ------
2021-05-02 19:59:38.896 T:1184548   DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2021-05-02 19:59:39.943 T:1184548   DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2021-05-02 19:59:46.814 T:1184548   DEBUG <general>: ------ Window Init (Pointer.xml) ------
2021-05-02 19:59:51.838 T:1184548   DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2021-05-02 20:00:34.637 T:1184709 WARNING <general>: DARWINOSX: underflow (0 vs 4096 bytes)
2021-05-02 20:00:44.734 T:1184640   DEBUG <general>: CCoreAudioStream::Close: Restoring original physical format for stream 0x002d. ([lpcm] Mixable Interleaved 2 Channel 24-bit Signed Integer LE (48000Hz))
2021-05-02 20:00:44.736 T:1184640   DEBUG <general>: CCoreAudioStream::SetPhysicalFormat: Physical format for stream 0x002d. now active ([lpcm] Mixable Interleaved 2 Channel 24-bit Signed Integer LE (48000Hz))
2021-05-02 20:00:44.736 T:1184640   DEBUG <general>: CCoreAudioStream::Close: Closed stream 0x002d.

**Describe the bug**

Real-Debrid seemed to quit working after the recent Seren update. In attempt to fix, I unauthorized and then tried to reauthorize. I am now unable to authorize Real-Debrid. I am briefly given the code to authorize, but then very quickly it goes away and gives me a Seren error.

**To Reproduce**
1. Unauthorize Real Debrid
2. Click to reauthorize real-debrid
3. See error

**Comment by CaptainSweatpants** [comment]
Same issue as of tonight, i cannot authorize RD, throws error (below).
Sometimes the error is thrown before the Code pop up is displayed, and other times its immediate the moment i hit authorize 

===========================================

2021-05-02 23:02:35.256 T:11013    INFO <general>: SEREN: SETTINGS UPDATED
2021-05-02 23:02:35.268 T:11013    INFO <general>: SEREN: FORCE REFRESHING WIDGETS
2021-05-02 23:02:36.052 T:11310    INFO <general>: SEREN: Seren, Running Path - {'action': 'authRealDebrid'}
2021-05-02 23:02:37.654 T:11310   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 247, in dispatch
                                                       real_debrid.RealDebrid().auth()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 80, in auth
                                                       response = self.session.get(url).json()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2021-05-02 23:02:37.972 T:11310    INFO <general>: Python interpreter stopped
2021-05-02 23:02:49.646 T:11317    INFO <general>: initializing python engine.
2021-05-02 23:02:50.460 T:11317    INFO <general>: SEREN: Seren, Running Path - {'action': 'openSettings', 'from_widget': 'false'}
2021-05-02 23:02:50.462 T:11317    INFO <general>: CPythonInvoker(23, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py): script successfully run
2021-05-02 23:02:50.773 T:11317    INFO <general>: Python interpreter stopped
2021-05-02 23:03:00.665 T:11323    INFO <general>: initializing python engine.
2021-05-02 23:03:00.682 T:11013    INFO <general>: SEREN: SETTINGS UPDATED
2021-05-02 23:03:00.692 T:11013    INFO <general>: SEREN: FORCE REFRESHING WIDGETS
2021-05-02 23:03:01.569 T:11323    INFO <general>: SEREN: Seren, Running Path - {'action': 'authRealDebrid'}
2021-05-02 23:03:02.111 T:11323   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 247, in dispatch
                                                       real_debrid.RealDebrid().auth()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 80, in auth
                                                       response = self.session.get(url).json()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
=======================================

Ive done the complete wipe, uninstall, reinstall etc etc.. PM authorizes fine, as well as trakt. 
Running Kodi 19 (latest) 
Nvidia Shield Pro 2020

**Comment by motosba** [comment]
Same error using Kodi 18.8 and Kodi 19 on Pop!_OS 20.10. Code is sometimes displayed as well.

   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=downloadManagerView&from_widget=false
   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/testuser/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/home/testuser/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 247, in dispatch
                                                real_debrid.RealDebrid().auth()
                                              File "/home/testuser/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 80, in auth
                                                response = self.session.get(url).json()
                                              File "/home/testuser/.kodi/addons/script.module.requests/lib/requests/models.py", line 889, in json
                                                self.content.decode(encoding), **kwargs
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by drinfernoo** [comment]
RD has been down tonight. See if it works tomorrow.

**Comment by BTrailor** [comment]
Still giving the same error tonight.

**Comment by drinfernoo** [comment]
@BTrailor RD has still been down 🤷🏼‍♀️

**Comment by BTrailor** [comment]
All good now.
