### ISSUE TITLE
[BUG] 2.1.3 - still getting trakt ID errors (trakt_season_id)

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#657]
I updated to 2.1.3 and have rebuilt my database several times and I am still getting issues with trakt_id's, particularly the trakt_season_id for a new show with only one season?

```
2021-07-23 19:47:36.479 T:17442    INFO <general>: SEREN (94): Seren, Running Path - {'action': 'getSources', 'smartPlay': 'false', 'source_select': 'true', 'forceresumecheck': 'true', 'action_args': {'episode': 6, 'season': 1, 'trakt_id': 4878263, 'trakt_show_id': 146535, 'mediatype': 'episode'}}
2021-07-23 19:47:39.423 T:17442   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'trakt_season_id'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 117, in dispatch
                                                       item_information = tools.get_item_information(action_args)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/common/tools.py", line 270, in get_item_information
                                                       action_args["trakt_id"], action_args["trakt_show_id"]
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 421, in get_episode
                                                       hide_watched=False
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 309, in get_episode_list
                                                       self._try_update_episodes(trakt_show_id, trakt_season_id, trakt_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 712, in _try_update_episodes
                                                       self._format_episodes(episodes_to_update)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/guard_decorators.py", line 38, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 672, in _format_episodes
                                                       for i in formatted_items
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 168, in execute_sql
                                                       return connection.execute_sql(query, data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 238, in execute_sql
                                                       return self._execute_query(_dumps(data), None, query)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 35, in wrapper
                                                       return [func(*args[:-1] + (i,), **kwargs) for i in args[-1]]
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 35, in <listcomp>
                                                       return [func(*args[:-1] + (i,), **kwargs) for i in args[-1]]
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py", line 672, in <genexpr>
                                                       for i in formatted_items
                                                   KeyError: 'trakt_season_id'
                                                   -->End of Python script error report<--
```

I took several nuclear options to fix it myself but it aint pretty:

smartplay.py

So this was just to capture an exception due to missing information?:

```
    def playlist_present_check(self, ignore_setting=False):
        """
        Confirms if a playlist is currently present. If not or playlist is for a different item, clear current list
        and build a new one
        :param ignore_setting: Force playlist building if setting is disabled
        :type ignore_setting: bool
        :return: Playlist if playlist is present else False
        :rtype: any
        """
        if g.get_bool_setting("smartplay.playlistcreate") or ignore_setting:

            try:
                if not self.item_information["info"]["mediatype"] == "episode":
                    g.log("Movie playback requested, clearing playlist")
                    g.PLAYLIST.clear()
                    return False
            #xbmc.log(str('SEREN_MODIFICATION')+'===>PHIL', level=xbmc.LOGINFO)
            except:
                return False
```

So this is where most of my "fix" is implemented

~/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/shows.py

So when it fails due to a missing trakt_season_id, I manually parse the sys.argv to get info (becasue I couldnt figure out in this context how to get the action_args any other way).
Then i get trakt connection details/headers/tokens from plugin.video.themoviedb.helper (so again because I know how to do this and dont know how serens trakt integration works)
Then I get the trakt season id from the season for the show (ie the api method for all seasons, and then the trakt id which corresponds to the season index position in the response (ie season number-1))
Then im manually updating the seren episodes and season db, as I thought this would surely fix the issue of that show having a missing season id.  And im doing it totally manually as again I couldnt figure out how to get your sql updates to actually work.
The "try_updates" thing still fails, dispite manually retrieving the actual correct season id for the show.

```
         try:
            self._try_update_episodes(trakt_show_id, trakt_season_id, trakt_id)
        except:

            #xbmc.log(str('SEREN_MODIFICATION')+'===>PHIL', level=xbmc.LOGINFO)
			import sys
			import xbmc
			#xbmc.log(str(sys.argv)+'===>PHIL', level=xbmc.LOGINFO)
			from urllib.parse import unquote
			action_vars = unquote(sys.argv[2])
			action_vars = action_vars.split('{')[1].split('}')[0]
			episode = action_vars.split('"episode":')[1].split(',')[0].strip()
			season = action_vars.split('"season":')[1].split(',')[0].strip()
			import requests
			import json
			import os
			from os.path import expanduser

			home = expanduser("~")
			import xml.etree.ElementTree as ET
			tree = ET.parse(home + '/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/settings.xml')
			root = tree.getroot()

			for child in root:
				if (child.attrib)['id'] == 'trakt_token':
					token = json.loads(child.text)

			home = expanduser("~")
			try:
				inFile = open(home + '/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/traktapi.py')
				for line in inFile:
					if 'self.client_id = ' in line:
						client_id = line.replace('self.client_id = ','').replace('\'','').replace('    ','').replace('\n', '')
					if 'self.client_secret = ' in line:
						client_secret = line.replace('self.client_secret = ','').replace('\'','').replace('    ','').replace('\n', '')
			except:
				inFile = open(home + '/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/trakt/api.py')
				for line in inFile:
					if 'CLIENT_ID = ' in line:
						client_id = line.replace('CLIENT_ID = ','').replace('\'','').replace('    ','').replace('\n', '')
					if 'CLIENT_SECRET = ' in line:
						client_secret = line.replace('CLIENT_SECRET = ','').replace('\'','').replace('    ','').replace('\n', '')

			inFile.close()

			headers = {'trakt-api-version': '2', 'trakt-api-key': client_id, 'Content-Type': 'application/json'}
			headers['Authorization'] = 'Bearer {0}'.format(token.get('access_token'))
			response = requests.get('https://api.trakt.tv/shows/'+str(trakt_show_id)+'/seasons', headers=headers).json()

			xbmc.log(str(response)+'===>PHIL', level=xbmc.LOGINFO)
			trakt_season_id = response[int(season)-1]['ids']['trakt']
			#self.execute_sql(
			#    "UPDATE episodes SET trakt_season_id=? WHERE trakt_show_id=? and season=?",
			#    (trakt_season_id, trakt_show_id,int(season)),
			#)
			#self.execute_sql(
			#    "UPDATE seasons SET trakt_id=? WHERE trakt_show_id=? and season=?", (trakt_season_id, trakt_show_id,int(season))
			#)

			import sqlite3
			con = sqlite3.connect('/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/traktSync.db')
			cur = con.cursor()

			update_sql = ("UPDATE episodes SET trakt_season_id="+str(trakt_season_id)+" WHERE trakt_show_id="+str(trakt_show_id)+" and season="+str(season))
			cur.execute(update_sql).fetchall()
			con.commit()

			update_sql = ("UPDATE seasons SET trakt_id="+str(trakt_season_id)+" WHERE trakt_show_id="+str(trakt_show_id)+" and season="+str(season))
			cur.execute(update_sql).fetchall()
			con.commit()

			cur.close()
			con.close()

			self._try_update_episodes(trakt_show_id, trakt_season_id, trakt_id)
```

So I then had to take further action when it still thinks there is no actual season id for the show, dispite the sql database having just been updaated.
So when that fails it gets the trakt show id from the formatted_items, because again in this context I coundnt figure out how to get the show_id back.
And then I manually retrieve the trakt_season_id from the sql database which I just updated, and then finally it can actually run "self.execute_sql(self.upsert_episode_query," without failing.

```
    @guard_against_none_or_empty()
    def _format_episodes(self, list_to_update):
        formatted_items = self._format_objects(self._identify_episodes_to_update(list_to_update))

        try:
            if formatted_items is None:
                return
            self.execute_sql(
                self.upsert_episode_query,
                (
                    (
                        i["info"]["trakt_id"],
                        i["info"]["trakt_show_id"],
                        i["info"]["trakt_season_id"],
                        None,
                        None,
                        i["info"].get("aired"),
                        i["info"].get("dateadded"),
                        i["info"].get("season"),
                        i["info"].get("episode"),
                        i["info"].get("tmdb_id"),
                        i["info"].get("tvdb_id"),
                        i["info"].get("imdb_id"),
                        i["info"],
                        i.get("art"),
                        i.get("cast"),
                        self._create_args(i),
                        None,
                        None,
                        self.metadataHandler.meta_hash,
                        i["info"]["trakt_id"],
                    )
                    for i in formatted_items
                ),
            )
        except:
            #xbmc.log(str('SEREN_MODIFICATION')+'===>PHIL', level=xbmc.LOGINFO)
            for i in formatted_items:
                #xbmc.log(str(i)+'===>PHIL', level=xbmc.LOGINFO)
                if 'tvshow.trakt_id' in str(i):
                    trakt_show_id = i['info']['tvshow.trakt_id']
                    break
            import sqlite3
            con = sqlite3.connect('/home/osmc/.kodi/userdata/addon_data/plugin.video.seren/traktSync.db')
            cur = con.cursor()
            sql = cur.execute('select * from seasons where trakt_show_id = ' + str(trakt_show_id)).fetchall()
            trakt_season_id = sql[0][0]

            if formatted_items is None:
                return
            self.execute_sql(
                self.upsert_episode_query,
                (
                    (
                        i["info"]["trakt_id"],
                        i["info"]["trakt_show_id"],
                        trakt_season_id,
                        None,
                        None,
                        i["info"].get("aired"),
                        i["info"].get("dateadded"),
                        i["info"].get("season"),
                        i["info"].get("episode"),
                        i["info"].get("tmdb_id"),
                        i["info"].get("tvdb_id"),
                        i["info"].get("imdb_id"),
                        i["info"],
                        i.get("art"),
                        i.get("cast"),
                        self._create_args(i),
                        None,
                        None,
                        self.metadataHandler.meta_hash,
                        i["info"]["trakt_id"],
                    )
                    for i in formatted_items
                ),
            )
            #xbmc.log(str('SEREN_MODIFICATION')+'===>PHIL', level=xbmc.LOGINFO)
```

So would it be possible to implement your own nuclear option that either totally ignores information which isnt necessarry to identify the episode (if you have the episode id why do you need the season id).
Or conversely a more rigouours precheck and lookup for any missing information so that incremental changes on trakt/brand new shows which mignt not have all the information available dont just fail.

**Comment by drinfernoo** [comment]
How about if you open either a) a normal bug report, complete with steps to reproduce and an error log (the template, basically), or b) a PR with your fixes?

Trying to wade through this to find out whether you're reporting a bug or proposing a fix is pretty tough...

**Comment by drinfernoo** [comment]
For what it's worth, "nuclear option" is usually not the terminology I'd use when referring to routine error handling...

**Comment by drinfernoo** [comment]
Can you try turning on "Hide Specials" and rebuilding the database?

**Comment by henryjfry** [comment]
**Describe the bug**
Attempting to watch season 01 episode 06 of loki from my library using tmdbhelper via seren, seren reports an error because trakt_season_id is not populated.
Previously similar errors for other shows (rick and morty season 5) have been resolved by rebuilding the database. I have just recently updated to the newest version of Seren and was testing a couple of more recent shows to see if the problem had been resolved and how it reacted with respect to hosters (see other bug). I have therefore rebuilt the database for the new version of seren and have rebuilt it at least 3 or 4 times in an effort to get the missing id to populate on its own.


**To Reproduce**
Steps to reproduce the behavior:
Watch season 01 episode 06 of Loki?
Not entirely sure how reproducable this problem is, as im not sure why the ID was not populated in the first place, I was able to retrieve the information and populate the database my self, so the particular ID was available.
I suspect its when the show is first populated to the DB and certain ID's dont yet exist, however as I have rebuilt the database after this particular season has ended and was also able to retrieve the offending information from trakt via an API call on the same day that doenst appear to be the case.

To reproduce the problem perhaps you would need to delete the season ID from a show and then attempt to watch an episode??
But I really dont know.

**Expected behavior**
I would expect that when seren isn't able to find the information which it needs to be able to play an episode from the DB it would update the DB then and there with the relevant show information so that it doesnt fail on the current action and works for that show going forward.

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
Im going to attach my full logs.

**Additional context**
No additional context, freshly rebuilt database with all the relevant information for the specific show available on trakt.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6872292/kodi.log)

**Comment by henryjfry** [comment]
I would open a PR but my solution is reliant upon tmdbhelper trakt tokens and inserting items into the database manually.
Both will be seren methods but I dont know how to use them so I implemented my own, just to get it working.

I think the actual error is just in:
def _format_episodes(self, list_to_update):

```
		if formatted_items is None:
			return
		self.execute_sql(
			self.upsert_episode_query,
			(
				(
					i["info"]["trakt_id"],
					i["info"]["trakt_show_id"],
					i["info"]["trakt_season_id"],
					None,
					None,
					i["info"].get("aired"),
					i["info"].get("dateadded"),
					i["info"].get("season"),
					i["info"].get("episode"),
					i["info"].get("tmdb_id"),
					i["info"].get("tvdb_id"),
					i["info"].get("imdb_id"),
					i["info"],
					i.get("art"),
					i.get("cast"),
					self._create_args(i),
					None,
					None,
					self.metadataHandler.meta_hash,
					i["info"]["trakt_id"],
				)
				for i in formatted_items
			),
		)
```
And specifically "i["info"]["trakt_season_id"]"

So a 'KeyError' exception and lookup for 'trakt_season_id' when it fails would capture this?

**Comment by drinfernoo** [comment]
Wouldn't it make more sense to just use `i["info"].get("trakt_season_id", "")` and call it a day?

That seems like a much more same method of handling a KeyError than to jump through hoops of having another add-on do lookups and stuff 😅

**Comment by henryjfry** [comment]
Well possibly but I think that piece of information is missing:

SEREN (94): Seren, Running Path - {'action': 'getSources', 'smartPlay': 'false', 'source_select': 'true', 'forceresumecheck': 'true', 'action_args': {'episode': 6, 'season': 1, 'trakt_id': 4878263, 'trakt_show_id': 146535, 'mediatype': 'episode'}}

So it would still fail?

I think my first change was just to ignore that particular error and see what happened and after that smart play was causing an exception with this:
"self.item_information["info"]["mediatype"] == "episode":"

As "none type is not subscriptable" (ie item_information["info"] or item_information was empty).
(lines 7004-7017)

But ill undo what I did and give that a go later, I'm just watching something there now.

**Comment by henryjfry** [comment]
Ok so I reset "smartPlay.py" and "trakt_sync/shows.py" back to default, rebuilt my database and attempted to play loki season 1 episode 6 and now it doesnt give an error, it just stops and returns the following in the log:

```
2021-07-24 14:33:52.723 T:20524    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.player - finished resolving path to url
                                                   plugin://plugin.video.seren/?action=getSources&smartPlay=false&source_select=true&forceresumecheck=true&actionArgs=%7B%22episode%22%3A%206%2C%20%22item_type%22%3A%20%22episode%22%2C%20%22season%22%3A%201%2C%20%22trakt_id%22%3A%20146535%7D
2021-07-24 14:33:52.724 T:20524    INFO <general>: CPythonInvoker(831, /home/osmc/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run
2021-07-24 14:33:52.751 T:20708    INFO <general>: initializing python engine.
2021-07-24 14:33:54.295 T:20524    INFO <general>: Python interpreter stopped
2021-07-24 14:33:56.935 T:20708    INFO <general>: SEREN (298): Seren, Running Path - {'action': 'getSources', 'smartPlay': 'false', 'source_select': 'true', 'forceresumecheck': 'true', 'action_args': {'episode': 6, 'season': 1, 'trakt_id': 4878263, 'trakt_show_id': 146535, 'mediatype': 'episode'}}
2021-07-24 14:34:13.707 T:20598    INFO <general>: CPythonInvoker(832, /home/osmc/.kodi/addons/plugin.video.seren/seren.py): script successfully run
2021-07-24 14:34:15.103 T:20598    INFO <general>: Python interpreter stopped
2021-07-24 14:34:15.941 T:1231    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.themoviedb.helper/?info=play&amp;type=episode&amp;tmdb_id=84958&amp;season=1&amp;episode=6]
2021-07-24 14:34:15.941 T:1231  WARNING <general>: Attempt to set unplayable index 0
2021-07-24 14:34:15.946 T:20708 WARNING <general>: SEREN (298): Cancelling non playlist playback
2021-07-24 14:34:16.011 T:20708    INFO <general>: CPythonInvoker(833, /home/osmc/.kodi/addons/plugin.video.seren/seren.py): script successfully run
2021-07-24 14:34:17.348 T:20708    INFO <general>: Python interpreter stopped

```

Trying it again with `i["info"].get("trakt_season_id", ""),` rather than `i["info"]["trakt_season_id"]` and it does work.

Im just rebuilding my database again, im going to see what happens with `i["info"].get("trakt_season_id", ""),` setup initially.

**Comment by henryjfry** [comment]
Ok so I get the same behaviour with "i["info"].get("trakt_season_id", ""),"
The first time nothing happens, the second time it will play like normal.

So I suppose thats okish but not ideal.
My own modifications do the same thing.

Ive been looking into it a bit and it seems like every other play it returns after `g.log("Cancelling non playlist playback", "warning")` in router, if it continues on and plays the file the next time it just returns and stops.

Now possibly this is because i have been selecting the same episodes to play via source select and then have not been playing anything. And therefore this has something to do with kodis resolveurl thing where it attempts to keep playing until a resolvable file is returned.
So this behaviour wouldnt be observed if something actually played in the meantime.

However I think I have a relatively simple solution, in `seren.py` after it returns from `router.py` do a short loop for a couple of seconds and if the persistent background isnt visible, or a file isnt playing, rerun the router dispatch request.  ie:

```
try:
    curr_time = time.time()
    with TimeLogger('{}'.format(g.REQUEST_PARAMS.get('action', ''))):
        router.dispatch(g.REQUEST_PARAMS)
    while time.time() - curr_time < 3:
        xbmc.log(str(1)+'===>PHIL', level=xbmc.LOGINFO)
        xbmc.sleep(1000)
        xbmc.log(str(2)+'===>PHIL', level=xbmc.LOGINFO)
        if not xbmc.Player().isPlaying() and not xbmc.getCondVisibility('Window.IsActive(persistent_background.xml)'):
            xbmc.log(str(3)+'===>PHIL', level=xbmc.LOGINFO)
            router.dispatch(g.REQUEST_PARAMS)
            xbmc.sleep(1000)
            g.deinit()
```

**Comment by drinfernoo** [comment]
Could you attempt a rebuild in 2.1.4 and see if this is still happening to you, without modifications?

**Comment by henryjfry** [comment]
I'll try that this evening

**Comment by henryjfry** [comment]
Ok so I think I know what is happening when I click to play an episode and it doesnt play

```
    def playlist_present_check(self, ignore_setting=False):
        if g.get_bool_setting("smartplay.playlistcreate") or ignore_setting:

            xbmc.log(str(g.REQUEST_PARAMS)+'===>PHIL', level=xbmc.LOGINFO)
            xbmc.log(str(self.item_information["info"])+'===>PHIL', level=xbmc.LOGINFO)

            #if 'episode' in str(g.REQUEST_PARAMS):
            #    self.item_information["info"]["mediatype"] = "episode"

            if not self.item_information["info"]["mediatype"] == "episode":
                g.log("Movie playback requested, clearing playlist")
                g.PLAYLIST.clear()
                return False
```

So with the above code in "/plugin.video.seren/resources/lib/modules/smartPlay.py" I played selected an episode which then didnt play and got this in the logs:

```
2021-08-05 19:45:07.086 T:4363     INFO <general>: {'action': 'getSources', 'smartPlay': 'false', 'source_select': 'true', 'forceresumecheck': 'true', 'action_args': {'episode': 4, 'season': 1, 'trakt_id': 4878243, 'trakt_show_id': 146535, 'mediatype': 'episode'}}===>PHIL
2021-08-05 19:45:07.093 T:4363     INFO <general>: {'episode': 4, 'sortepisode': 4, 'season': 1, 'sortseason': 1, 'year': '2021', 'premiered': '2021-06-30T07:00:00', 'aired': '2021-06-30T07:00:00', 'imdbnumber': 'tt10161340', 'imdb_id': 'tt10161340', 'trakt_id': 4878243, 'tvdb_id': 8452518, 'tmdb_id': 2927204, 'duration': 3120, 'dateadded': '2021-08-05T11:58:20', 'rating': 8.21, 'votes': 3197, 'rating.trakt': {'rating': 8.21, 'votes': 3197}, 'mediatype': 'episode', 'available_translations': ['cs', 'de', 'en', 'es', 'fr', 'hu', 'it', 'pl', 'pt', 'ru', 'sk', 'sv', 'tr', 'zh'], 'title': 'The Nexus Event', 'originaltitle': 'The Nexus Event', 'sorttitle': 'The Nexus Event', 'plot': 'Frayed nerves and paranoia infiltrate the TVA as Mobius and Hunter B-15 search for Loki and Sylvie.', 'plotoutline': 'Frayed nerves and paranoia infiltrate the TVA as Mobius and Hunter B-15 search for Loki and Sylvie.', 'trakt_show_id': 146535, 'tmdb_show_id': 84958, 'tvdb_show_id': 362472, 'trakt_season_id': 236317, 'tvshowtitle': 'Loki', 'playcount': 1, 'last_watched_at': '2021-07-16T21:05:39', 'director': ['Kate Herron'], 'writer': ['Bisha K. Ali', 'Elissa Karasik', 'Eric Martin'], 'overview': 'Frayed nerves and paranoia infiltrate the TVA as Mobius and Hunter B-15 search for Loki and Sylvie.', 'rating.tmdb': {'rating': 8.4, 'votes': 18}, 'rating.tvdb': {'rating': 0, 'votes': 0}, 'mpaa': 'TV-14', 'genre': ['Action', 'Adventure', 'Fantasy'], 'country': 'United States', 'rating.imdb': {'rating': 9.4, 'votes': 15846}, 'tvshow.year': '2021', 'studio': ['Marvel Studios'], 'country_origin': 'US', 'aliases': ["Marvel Studios' Loki"], 'tvshow.imdb_id': 'tt9140554', 'tvshow.trakt_id': 146535, 'tvshow.tvdb_id': 362472, 'tvshow.tmdb_id': 84958}===>PHIL
2021-08-05 19:45:07.161 T:1278    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.themoviedb.helper/?info=play&amp;type=episode&amp;tmdb_id=84958&amp;season=1&amp;episode=4]
2021-08-05 19:45:07.161 T:1278  WARNING <general>: Attempt to set unplayable index 0
2021-08-05 19:45:07.168 T:4363  WARNING <general>: SEREN (176): Cancelling non playlist playback
2021-08-05 19:45:07.263 T:4363     INFO <general>: CPythonInvoker(681, /home/osmc/.kodi/addons/plugin.video.seren/seren.py): script successfully run
2021-08-05 19:45:08.714 T:4363     INFO <general>: Python interpreter stopped

```
Note both "g.REQUEST_PARAMS" and "self.item_information["info"]" contain 'mediatype': 'episode'
Howeve I think self.item_information["info"]["mediatype"] == "episode" is coming back true possibly due to a unicode/bytestring/python3 issue.

When I uncomment:

```
            if 'episode' in str(g.REQUEST_PARAMS):
                self.item_information["info"]["mediatype"] = "episode"
```
It all works as expected (ie no
