### ISSUE TITLE
[BUG] Seren- Error on Start

### ISSUE THREAD

**Issue by NaomiErin** [nixgates/plugin.video.seren#769]
**Describe the bug**

Error pop up every time I launch Kodi

**Log**

```
2022-05-15 19:27:31.654 T:8564    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'providers.a4kScrapers.temp'
                                                   Traceback (most recent call last):
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\router.py", line 748, in dispatch
                                                       ProvidersServiceManager().run_long_life_manager()
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\providers\service_manager.py", line 20, in __init__
                                                       super(ProvidersServiceManager, self).__init__()
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\providers\__init__.py", line 48, in __init__
                                                       self._init_providers()
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\providers\__init__.py", line 57, in _init_providers
                                                       self.update_known_providers()
                                                     File "**********************\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\providers\__init__.py", line 103, in update_known_providers
                                                       all_providers = providers.get_all(self.language)
                                                     File "**********************\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.seren\providers\__init__.py", line 64, in get_all
                                                       return _get_providers(language)
                                                     File "**********************\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.seren\providers\__init__.py", line 44, in _get_providers
                                                       provider_list = __import__(providers_path, fromlist=[''])
                                                   ModuleNotFoundError: No module named 'providers.a4kScrapers.temp'
                                                   -->End of Python script error report<--
```
**To Reproduce**

Steps to reproduce the behavior, for example:

**Expected behavior**

No Error Pop Up

**Environment**

 - Operating System: [Windows 10]
 - Kodi Version -[Kodi 19.4]
 - Seren Version [2.1.9]

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by drinfernoo** [comment]
What version of a4kScrapers do you have?

**Comment by NaomiErin** [comment]
> What version of a4kScrapers do you have?

Not sure. Every time I click manage provider package it throws up the error and freezes

**Comment by drinfernoo** [comment]
@NaomiErin The only thing I can think is that maybe you have a corrupted `providers.db` file... Try deleting it (and the associated `.md5` file) from `special://userdata/addon_data/plugin.video.seren/`, and then reinstall a4kScrapers.
