### ISSUE TITLE
[BUG] Seren 2.2.0 - Database errors after update + userdata wipe

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#778]
So when I updated to 2.2.0 it indicated that seren had previously been manually installed and did I want to wipe my addon data. I clicked yes and when I tried to run seren to play an episode was mostly getting an error relating to the "skins" table not existing.

After that I started trying to delete the db files and/or wipe my userdata completely and it gave all sorts of other errors.
It only started working again when I manually restored a backup of my userdata.

Im not sure if the initial error occured after a failed trakt sync but as you can see from the logs there were numerous errors reporting tables not existing, columns not existing and I would have hoped any improvements around the databases would have fixed this issue where when stuff is missing it just fails.
I'd been hoping that in event of table failure like this it just gets wiped, recreated and whatever lookup was failing gets totally repopulated and a scheculed full sync.

Rather than not finding an episode id, season id, show id in the database failing and then not fixing the obvious sync failure through the nuclear option of completely removing a messed up table and creating a valid one from scratch.

https://pastebin.com/PVudFPBB

Or in the event of the a db failure, resort to a live trakt lookup or just not using trakt data at all.
If an episode doesnt scrobble thats less of a deal than if an episode wont play because it is missing one ID when it has plenty of other metadata to identify the specific show passed to it from the original play url.

**Comment by drinfernoo** [comment]
What I see here are:
```python
2022-06-01 15:54:39.557 T:7187    ERROR <general>: SEREN (-1): Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0xc6cb7250>, '/oauth/token', {'refresh_token': '4f5b7d73f03fadab034c51cffd37b1be63664504c1598797c6ff561ca6e62506', 'client_id': '0128c95089a7b58477204806a1b62ee130182b48c121c1eb9fe1d37b915fc5cb', 'client_secret': '8f2ae1d28337020f0bcd1e60cc036762ecd39f5e49ec35a85a3f5c7d54811ec1', 'redirect_uri': 'urn:ietf:wg:oauth:2.0:oob', 'grant_type': 'refresh_token'}) - {}
2022-06-01 15:54:39.558 T:7187    ERROR <general>: SEREN (-1): Unable to refresh Trakt auth
2022-06-01 15:54:39.559 T:7187    ERROR <general>: SEREN (-1): Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0xc6cb7250>, 'sync/playback/episodes') - {'extended': 'full', 'timeout': 60, 'limit': 50}
2022-06-01 15:54:39.559 T:7187    ERROR <general>: SEREN (-1): Unable to refresh Trakt auth
2022-06-01 15:54:39.561 T:7187    ERROR <general>: SEREN (-1): Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/activities.py", line 204, in _sync_show_bookmarks
                                                       self._sync_bookmarks("episodes")
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/activities.py", line 566, in _sync_bookmarks
                                                       "sync/playback/{}".format(bookmark_type), extended="full", timeout=60, limit=50, ignore_cache=True
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 782, in get_all_pages_json
                                                       for response in self._get_all_pages(get_method, url, **params):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 758, in _get_all_pages
                                                       response = func(url, **params)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 129, in wrapper
                                                       method_class.try_refresh_token(True)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 587, in try_refresh_token
                                                       "grant_type": "refresh_token",
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 106, in wrapper
                                                       raise Exception("Unable to refresh Trakt auth")
                                                   Exception: Unable to refresh Trakt auth
 
                                                   Unable to refresh Trakt auth
2022-06-01 15:54:39.561 T:7187     INFO <general>: SEREN (-1): Failed to sync activity: Show bookmarks - Unable to refresh Trakt auth
```
and then a whole bunch of stuff like this:
```python
2022-06-01 15:54:45.352 T:7187    ERROR <general>: SEREN (-1): HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/ratings/shows?extended=full&limit=50&page=1 (Caused by ResponseError('too many 500 error responses'))
2022-06-01 15:54:45.367 T:7187    ERROR <general>: SEREN (-1): Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 449, in send
                                                       timeout=timeout
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 859, in urlopen
                                                       **response_kw
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 859, in urlopen
                                                       **response_kw
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 859, in urlopen
                                                       **response_kw
                                                     [Previous line repeated 1 more time]
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 836, in urlopen
                                                       retries = retries.increment(method, url, response=response, _pool=self)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/ratings/shows?extended=full&limit=50&page=1 (Caused by ResponseError('too many 500 error responses'))
 
                                                   During handling of the above exception, another exception occurred:
 
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/activities.py", line 433, in _sync_rated_shows
                                                       trakt_rated_shows = list(itertools.chain.from_iterable(trakt_rated_shows))
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 782, in get_all_pages_json
                                                       for response in self._get_all_pages(get_method, url, **params):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 758, in _get_all_pages
                                                       response = func(url, **params)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 92, in wrapper
                                                       response = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 642, in get
                                                       timeout=timeout,
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 507, in send
                                                       raise RetryError(e, request=request)
                                                   requests.exceptions.RetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/ratings/shows?extended=full&limit=50&page=1 (Caused by ResponseError('too many 500 error responses'))
 
                                                   HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/ratings/shows?extended=full&limit=50&page=1 (Caused by ResponseError('too many 500 error responses'))
2022-06-01 15:54:45.367 T:7187     INFO <general>: SEREN (-1): Failed to sync activity: Shows ratings - HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/ratings/shows?extended=full&limit=50&page=1 (Caused by ResponseError('too many 500 error responses'))
2022-06-01 15:54:45.370 T:7187     INFO <general>: SEREN (-1): Running Activity: Hidden Movies
2022-06-01 15:54:45.923 T:7314    ERROR <general>: SEREN (-1): Trakt returned a 401 (Unauthorized - OAuth must be provided): while requesting https://api.trakt.tv/users/hidden/progress_watched_reset
2022-06-01 15:54:45.938 T:7313    ERROR <general>: SEREN (-1): Trakt returned a 401 (Unauthorized - OAuth must be provided): while requesting https://api.trakt.tv/users/hidden/progress_watched
2022-06-01 15:54:45.972 T:7312    ERROR <general>: SEREN (-1): Trakt returned a 401 (Unauthorized - OAuth must be provided): while requesting https://api.trakt.tv/users/hidden/calendar
2022-06-01 15:54:45.976 T:7315    ERROR <general>: SEREN (-1): Trakt returned a 401 (Unauthorized - OAuth must be provided): while requesting https://api.trakt.tv/users/hidden/progress_collected
2022-06-01 15:54:46.238 T:7316    ERROR <general>: SEREN (-1): Trakt returned a 401 (Unauthorized - OAuth must be provided): while requesting https://api.trakt.tv/users/hidden/recommendations
```
Which indicates to me that you simply need to reauthorize Trakt.

**Comment by henryjfry** [comment]
Yeah that was an error also which happened as soon as I updated.  I think because my prior authentication was setup as trakt client/secret so when my settings were wiped it lost that authentication.

However if you see in the logs I disabled and renabled the addon at least a couple of times after authenticating, to try and trigger whatever startup routine seren doesn.

And I also tried rebuilding the database at least a couple of times and still had issues like:

                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: no such table: skins
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 814, in dispatch
                                                       run_maintenance()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/common/maintenance.py", line 237, in run_maintenance
                                                       update_themes()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/common/maintenance.py", line 30, in update_themes
                                                       SkinManager().check_for_updates(silent=True)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/skinManager/__init__.py", line 48, in __init__
                                                       self.installed_skins = self._get_all_installed()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/skinManager/__init__.py", line 132, in _get_all_installed
                                                       return self.fetchall("SELECT * FROM skins")
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 169, in fetchall
                                                       return connection.fetchall(query, data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 241, in fetchall
                                                       return self._execute_query(_dumps(data), "fetchall", query)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 34, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 274, in _execute_query
                                                       self._retry_handler(e)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 328, in _retry_handler
                                                       super(SQLiteConnection, self)._retry_handler(exception)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 251, in _retry_handler
                                                       raise exception
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 264, in _execute_query
                                                       self._cursor.execute(query)
                                                   sqlite3.OperationalError: no such table: skins
                                                   -->End of Python script error report<--
 
2022-06-01 16:39:41.686 T:9073     INFO <general>: Python interpreter stopped
2022-06-01 16:39:50.911 T:9075     INFO <general>: initializing python engine.
2022-06-01 16:39:52.480 T:9075     INFO <general>: SEREN (-1): Seren, Running Path - {'action': 'syncTraktActivities'}
2022-06-01 16:39:52.686 T:9075    ERROR <general>: SEREN (-1): SELECT * FROM activities WHERE sync_id=1
2022-06-01 16:39:52.696 T:9075    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: no such table: activities
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 580, in dispatch
                                                       TraktSyncDatabase().sync_activities()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/activities.py", line 24, in __init__
                                                       super(TraktSyncDatabase, self).__init__()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/__init__.py", line 316, in __init__
                                                       self.refresh_activities()
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/trakt_sync/__init__.py", line 376, in refresh_activities
                                                       "SELECT * FROM activities WHERE sync_id=1"
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 173, in fetchone
                                                       return connection.fetchone(query, data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 244, in fetchone
                                                       return self._execute_query(_dumps(data), "fetchone", query)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 34, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 274, in _execute_query
                                                       self._retry_handler(e)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 328, in _retry_handler
                                                       super(SQLiteConnection, self)._retry_handler(exception)
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 251, in _retry_handler
                                                       raise exception
                                                     File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/database/__init__.py", line 264, in _execute_query
                                                       self._cursor.execute(query)
                                                   sqlite3.OperationalError: no such table: activities
                                                   -->End of Python script error report<--
