### ISSUE TITLE
[BUG] Seren Error Notification in Kodi Omega v21 - Alpha 1

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#895]
Hi,

I was testing Kodi Omega v21 - Alpha 1 and I know it's still in Alpha stage but I thought of letting you know about this error even if you might already be aware of it. Every time I start Kodi Omega v21 - Alpha 1 a Seren error notification pops up. This even happens when I try to install or update Seren from the Nixgates Repo. Could you please check and advise?

Here's my Kodi log:

https://paste.kodi.tv/ecicabiref

Thanks and Regards,
ShibajiCh.

**Comment by drinfernoo** [comment]
```python
2023-02-08 09:51:26.475 T:12783   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'Unsupported kodi version'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/service.py", line 39, in <module>
                                                       g.clear_kodi_bookmarks()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 661, in clear_kodi_bookmarks
                                                       with self.get_kodi_video_db_connection() as video_database:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 613, in get_kodi_video_db_connection
                                                       config = self.get_kodi_video_db_config()
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 636, in get_kodi_video_db_config
                                                       result = {"type": "sqlite3", "database": f"MyVideos{self.get_kodi_database_version()}"}
                                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 633, in get_kodi_database_version
                                                       raise KeyError("Unsupported kodi version")
                                                   KeyError: 'Unsupported kodi version'
                                                   -->End of Python script error report<--
```

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

Yes, I saw that error too. So does that mean Seren is not supported in Kodi Omega? Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Quihico** [comment]
Error is due to kodi V21 not being included in the "valid" versions of kodi for Seren as determined in ~plugin.video.seren/resources/lib/modules/globals.py line 623:  get_kodi_database_version-function, 
to fix: add
"
        elif self.KODI_VERSION == 21:
            return "121"
"
the "121" was determined by checking the MyVideos-name in userdata/Database-folder.

**Comment by ShibajiCh** [comment]
Hi @Quihico,

Okay. Thank you for the solution!

@drinfernoo: Hope you'll add this fix to future Seren releases.

Thanks and Regards,
ShibajiCh.

**Comment by drinfernoo** [comment]
That "fix" may allow this particular error to be bypassed, but none of the codebase has been tested in Kodi 21 Omega.

We plan to maintain our current support strategy, which is to ideally support two major Kodi versions, but we won't be focusing on Omega support until it is at least in RC status.

**Comment by ShibajiCh** [comment]
> That "fix" may allow this particular error to be bypassed, but none of the codebase has been tested in Kodi 21 Omega.
> 
> We plan to maintain our current support strategy, which is to ideally support two major Kodi versions, but we won't be focusing on Omega support until it is at least in RC status.

Hi @drinfernoo,

That's fine. I just wanted to inform you about this issue as I noticed it while testing Kodi Omega. I'm happy with Nexus at present and have no plans to shift to Omega until it's in RC stage.

Thanks and Regards,
ShibajiCh.

**Comment by shaktoo1** [comment]
I am using Omega Beta 2 as daily driver with seren and besides the start up error there has been no other issues. I will use this temp fix to get rid of this error Thanks .

**Comment by shaktoo1** [comment]
Hmm the error returned even though i had applied the workaround ? any idea 

2024-01-05 14:52:19.537 T:9440    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'Unsupported kodi version'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.seren\service.py", line 39, in <module>
                                                       g.clear_kodi_bookmarks()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 661, in clear_kodi_bookmarks
                                                       with self.get_kodi_video_db_connection() as video_database:
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 613, in get_kodi_video_db_connection
                                                       config = self.get_kodi_video_db_config()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 636, in get_kodi_video_db_config
                                                       result = {"type": "sqlite3", "database": f"MyVideos{self.get_kodi_database_version()}"}
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\globals.py", line 633, in get_kodi_database_version
                                                       raise KeyError("Unsupported kodi version")
                                                   KeyError: 'Unsupported kodi version'
                                                   -->End of Python script error report<--

**Comment by npmstart-pray** [comment]
Kodi v21 is rapidly approaching release (I seem to recall there's a beta or two out), so let the good doc get their ducks in a row for the release and subsequent Seren update. Troubleshooting/patching a workaround error will probably only distract them.

**Comment by Nuklear92** [comment]
> Kodi v21 is rapidly approaching release (I seem to recall there's a beta or two out), so let the good doc get their ducks in a row for the release and subsequent Seren update. Troubleshooting/patching a workaround error will probably only distract them. 

Kodi v21 is in the Beta 2 currently, soon going into Beta 3 or RC (Release Candidate) who knows, but it's not super far at this point for the official public release. And I personally had been using Beta 2 and is very stable. 👍 I find it odd that Seren hasn't release a patch or support for Kodi 21 at this point. 🤷‍♂️

**Comment by npmstart-pray** [comment]
The doc was clear that they only support 2 versions of kodi, so perhaps they’re worried about any potential backlash when v19 users are stranded. I would take this as their notice to prepare to upgrade or migrate elsewhere. Sent from nowhere near my ready room with my new tricorderOn Jan 6, 2024, at 14:14, Nuklear92 ***@***.***> wrote:﻿

Kodi v21 is rapidly approaching release (I seem to recall there's a beta or two out), so let the good doc get their ducks in a row for the release and subsequent Seren update. Troubleshooting/patching a workaround error will probably only distract them.

Kodi v21 is in the Beta 2 currently, soon going into Beta 3 or RC (Release Candidate) who knows, but it's not super far at this point for the official public release. And I personally had been using Beta 2 and is very stable. 👍 I find it odd that Seren hasn't release a patch or support for Kodi 21 at this point. 🤷‍♂️

**Comment by xboxhaxorz** [comment]
> Error is due to kodi V21 not being included in the "valid" versions of kodi for Seren as determined in ~plugin.video.seren/resources/lib/modules/globals.py line 623: get_kodi_database_version-function, to fix: add " elif self.KODI_VERSION == 21: return "121" " the "121" was determined by checking the MyVideos-name in userdata/Database-folder.

I dont have that resources folder in mine, i just have providermedia, providermodules and provider folder
This is a fresh seren install

**Comment by sunlollyking** [comment]
Is this going to be fixed now that Omega 21 final is out ?

**Comment by npmstart-pray** [comment]
It has not, and may never be by nixhates. Somebody else has managed to make it work, however. Poke around on the interwebz and you should come across the potential solution for you. Sent from my latest communicator device somewhere in space. On May 2, 2024, at 14:32, Chris Dixon ***@***.***> wrote:﻿
Is this going to be fixed now that Omega 21 final is out ?

**Comment by ib1ub12** [comment]
so i am wondering if the dev of seren is going to update the app now that omega is out and stable. tonight i cant even get into my COLLECTION in tv shows, its keeps giving me an error. Not sure where to look for guidance or updated info

**Comment by npmstart-pray** [comment]
I’m likely mistaken, but I thought others were using it on kodi 21. Have you tried to uninstall/reinstall?Sent from my latest communicator device somewhere in space. On May 14, 2024, at 22:39, ib1ub12 ***@***.***> wrote:﻿
so i am wondering if the dev of seren is going to update the app now that omega is out and stable. tonight i cant even get into my COLLECTION in tv shows, its keeps giving me an error. Not sure where to look for guidance or updated info

**Comment by ib1ub12** [comment]
i tried to update the repo and addon.  repo updates fin e but the add on throws and error and even tried to install on a new device, same thing is happening

**Comment by rayman705** [comment]
Hi. I have the same error every time I start Kodi Omega 21
