### ISSUE TITLE
Kodi 20.2 Crashing lately log error message [BUG]

### ISSUE THREAD

**Issue by Shredder5262** [nixgates/plugin.video.seren#938]
This is third hand info from my fiance, but it has been reported that after every TV episode kodi crashes. Upon reviewing a crash error log i see this error message in the log 

`
4-05-19 12:58:08.508 T:6980     info <general>: Skipped 23 duplicate messages..
2024-05-19 12:58:08.508 T:6980    error <general>: SEREN (32): Traceback (most recent call last):
                                                     File "C:\Users\Andrew\Documents\Kodi\portable_data\addons\plugin.video.seren\resources\lib\modules\player.py", line 559, in _handle_bookmark
                                                       g.clear_kodi_bookmarks()
                                                     File "C:\Users\Andrew\Documents\Kodi\portable_data\addons\plugin.video.seren\resources\lib\modules\globals.py", line 662, in clear_kodi_bookmarks
                                                       if file_ids := [
                                                     File "C:\Users\Andrew\Documents\Kodi\portable_data\addons\plugin.video.seren\resources\lib\modules\globals.py", line 663, in <listcomp>
                                                       str(i["idFile"])
                                                   TypeError: tuple indices must be integers or slices, not str
                                                   

`

**Comment by npmstart-pray** [comment]
Kodi v21 Omega is out, but it "breaks" Seren. There are workarounds published. 
Failing that, have you considered upgrading Kodi to just prior to v21 to see if that resolves your issue?  If it doesn't, you might want to note that Seren doesn't seem to be in active development any longer, so a change to an addon that is might be warranted. Umbrella is popular, and whatever version of fen or fen Light is too...

**Comment by Shredder5262** [comment]
> Kodi v21 Omega is out, but it "breaks" Seren. There are workarounds published. Failing that, have you considered upgrading Kodi to just prior to v21 to see if that resolves your issue? If it doesn't, you might want to note that Seren doesn't seem to be in active development any longer, so a change to an addon that is might be warranted. Umbrella is popular, and whatever version of fen or fen Light is too...

Those are some good suggestions. I never considered upgrading to 20.9, but i certainly look into that. I had not heard of umbrella or fen. I'll look into those as well. TBH i don't use Seren at all, but family members use it and are accustomed to the layout and how it works, so if those other addon's you mentioned look/function similarly, I'll consider switching over to those.

**Comment by npmstart-pray** [comment]
The learning curve for Umbrella isn't that steep. They're all similar enough - but some take customization better than others.
